using System;
using System.Collections.Generic;
using WSViews.Models;
using System.Linq;
namespace WSViews.Classes
{
    public static class ProvideCountries
    {
        public static IList<Country> Info()
        {
            IList<Country> countries = new List<Country>();

            //countries.Add(new Country { Name = "Afghanistan", ISO2 = "AF", ISO3 = "AFG", PhoneCode = "93", Continent = "Asia", Capital = "Kabul", TimeZone = "Asia/Kabul", Currency = "Afghani", Language = "fa-AF,ps,uz-AF,tk", LangDescrip = "Afghan Persian or Dari (official) 50%, Pashto (official) 35%, Turkic languages (primarily Uzbek and Turkmen) 11%, 30 minor languages (primarily Balochi and Pashai) 4%, much bilingualism, but Dari functions as the lingua franca", Mobile = "18000000", LandLine = "13500" });
            //countries.Add(new Country { Name = "Albania", ISO2 = "AL", ISO3 = "ALB", PhoneCode = "355", Continent = "Europe", Capital = "Tirana", TimeZone = "Europe/Tirane", Currency = "Lek", Language = "sq,el", LangDescrip = "Albanian 98.8% (official - derived from Tosk dialect), Greek 0.5%, other 0.6% (including Macedonian, Roma, Vlach, Turkish, Italian, and Serbo-Croatian), unspecified 0.1% (2011 est.)", Mobile = "3500000", LandLine = "312000" });
            //countries.Add(new Country { Name = "Algeria", ISO2 = "DZ", ISO3 = "DZA", PhoneCode = "213", Continent = "Africa", Capital = "Algiers", TimeZone = "Africa/Algiers", Currency = "Dinar", Language = "ar-DZ", LangDescrip = "Arabic (official), French (lingua franca), Berber dialects: Kabylie Berber (Tamazight), Chaouia Berber (Tachawit), Mzab Berber, Tuareg Berber (Tamahaq)", Mobile = "37692000", LandLine = "3200000" });
            //countries.Add(new Country { Name = "American Samoa", ISO2 = "AS", ISO3 = "ASM", PhoneCode = "1-684", Continent = "Oceania", Capital = "Pago Pago", TimeZone = "Pacific/Pago_Pago", Currency = "Dollar", Language = "en-AS,sm,to", LangDescrip = "Samoan 90.6% (closely related to Hawaiian and other Polynesian languages), English 2.9%, Tongan 2.4%, other Pacific islander 2.1%, other 2%", Mobile = "", LandLine = "10000" });
            //countries.Add(new Country { Name = "Andorra", ISO2 = "AD", ISO3 = "AND", PhoneCode = "376", Continent = "Europe", Capital = "Andorra la Vella", TimeZone = "Europe/Andorra", Currency = "Euro", Language = "ca", LangDescrip = "Catalan (official), French, Castilian, Portuguese", Mobile = "65000", LandLine = "39000" });
            //countries.Add(new Country { Name = "Angola", ISO2 = "AO", ISO3 = "AGO", PhoneCode = "244", Continent = "Africa", Capital = "Luanda", TimeZone = "Africa/Luanda", Currency = "Kwanza", Language = "pt-AO", LangDescrip = "Portuguese (official), Bantu and other African languages", Mobile = "9800000", LandLine = "303000" });
            //countries.Add(new Country { Name = "Anguilla", ISO2 = "AI", ISO3 = "AIA", PhoneCode = "1-264", Continent = "North America", Capital = "The Valley", TimeZone = "America/Anguilla", Currency = "Dollar", Language = "en-AI", LangDescrip = "English (official)", Mobile = "26000", LandLine = "6000" });
            //countries.Add(new Country { Name = "Antarctica", ISO2 = "AQ", ISO3 = "ATA", PhoneCode = "672", Continent = "Antarctica", Capital = "", TimeZone = "Antarctica/Troll", Currency = "", Language = "", LangDescrip = "", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Antigua and Barbuda", ISO2 = "AG", ISO3 = "ATG", PhoneCode = "1-268", Continent = "North America", Capital = "St. John's", TimeZone = "America/Antigua", Currency = "Dollar", Language = "en-AG", LangDescrip = "English (official), local dialects", Mobile = "179800", LandLine = "35000" });
            //countries.Add(new Country { Name = "Argentina", ISO2 = "AR", ISO3 = "ARG", PhoneCode = "54", Continent = "South America", Capital = "Buenos Aires", TimeZone = "America/Argentina/Buenos_Aires", Currency = "Peso", Language = "es-AR,en,it,de,fr,gn", LangDescrip = "Spanish (official), Italian, English, German, French, indigenous (Mapudungun, Quechua)", Mobile = "58600000", LandLine = "1" });
            //countries.Add(new Country { Name = "Armenia", ISO2 = "AM", ISO3 = "ARM", PhoneCode = "374", Continent = "Asia", Capital = "Yerevan", TimeZone = "Asia/Yerevan", Currency = "Dram", Language = "hy", LangDescrip = "Armenian (official) 97.9%, Kurdish (spoken by Yezidi minority) 1%, other 1% (2011 est.)", Mobile = "3223000", LandLine = "584000" });
            //countries.Add(new Country { Name = "Aruba", ISO2 = "AW", ISO3 = "ABW", PhoneCode = "297", Continent = "North America", Capital = "Oranjestad", TimeZone = "America/Aruba", Currency = "Guilder", Language = "nl-AW,es,en", LangDescrip = "Papiamento (a Spanish-Portuguese-Dutch-English dialect) 69.4%, Spanish 13.7%, English (widely spoken) 7.1%, Dutch (official) 6.1%, Chinese 1.5%, other 1.7%, unspecified 0.4% (2010 est.)", Mobile = "135000", LandLine = "43000" });
            //countries.Add(new Country { Name = "Australia", ISO2 = "AU", ISO3 = "AUS", PhoneCode = "61", Continent = "Oceania", Capital = "Canberra", TimeZone = "Australia/Sydney", Currency = "Dollar", Language = "en-AU", LangDescrip = "English 76.8%, Mandarin 1.6%, Italian 1.4%, Arabic 1.3%, Greek 1.2%, Cantonese 1.2%, Vietnamese 1.1%, other 10.4%, unspecified 5% (2011 est.)", Mobile = "24400000", LandLine = "10470000" });
            //countries.Add(new Country { Name = "Austria", ISO2 = "AT", ISO3 = "AUT", PhoneCode = "43", Continent = "Europe", Capital = "Vienna", TimeZone = "Europe/Vienna", Currency = "Euro", Language = "de-AT,hr,hu,sl", LangDescrip = "German (official nationwide) 88.6%, Turkish 2.3%, Serbian 2.2%, Croatian (official in Burgenland) 1.6%, other (includes Slovene, official in Carinthia, and Hungarian, official in Burgenland) 5.3% (2001 census)", Mobile = "13590000", LandLine = "3342000" });
            //countries.Add(new Country { Name = "Azerbaijan", ISO2 = "AZ", ISO3 = "AZE", PhoneCode = "994", Continent = "Asia", Capital = "Baku", TimeZone = "Asia/Baku", Currency = "Manat", Language = "az,ru,hy", LangDescrip = "Azerbaijani (Azeri) (official) 92.5%, Russian 1.4%, Armenian 1.4%, other 4.7% (2009 est.)", Mobile = "10125000", LandLine = "1734000" });
            //countries.Add(new Country { Name = "Bahamas", ISO2 = "BS", ISO3 = "BHS", PhoneCode = "1-242", Continent = "North America", Capital = "Nassau", TimeZone = "America/Nassau", Currency = "Dollar", Language = "en-BS", LangDescrip = "English (official), Creole (among Haitian immigrants)", Mobile = "254000", LandLine = "137000" });
            //countries.Add(new Country { Name = "Bahrain", ISO2 = "BH", ISO3 = "BHR", PhoneCode = "973", Continent = "Asia", Capital = "Manama", TimeZone = "Asia/Bahrain", Currency = "Dinar", Language = "ar-BH,en,fa,ur", LangDescrip = "Arabic (official), English, Farsi, Urdu", Mobile = "2125000", LandLine = "290000" });
            //countries.Add(new Country { Name = "Bangladesh", ISO2 = "BD", ISO3 = "BGD", PhoneCode = "880", Continent = "Asia", Capital = "Dhaka", TimeZone = "Asia/Dhaka", Currency = "Taka", Language = "bn-BD,en", LangDescrip = "Bangla (official, also known as Bengali), English", Mobile = "97180000", LandLine = "962000" });
            //countries.Add(new Country { Name = "Barbados", ISO2 = "BB", ISO3 = "BRB", PhoneCode = "1-246", Continent = "North America", Capital = "Bridgetown", TimeZone = "America/Barbados", Currency = "Dollar", Language = "en-BB", LangDescrip = "English (official), Bajan (English-based creole language, widely spoken in informal settings)", Mobile = "347000", LandLine = "144000" });
            //countries.Add(new Country { Name = "Belarus", ISO2 = "BY", ISO3 = "BLR", PhoneCode = "375", Continent = "Europe", Capital = "Minsk", TimeZone = "Europe/Minsk", Currency = "Ruble", Language = "be,ru", LangDescrip = "Belarusian (official) 23.4%, Russian (official) 70.2%, other 3.1% (includes small Polish- and Ukrainian-speaking minorities), unspecified 3.3% (2009 est.)", Mobile = "10675000", LandLine = "4407000" });
            //countries.Add(new Country { Name = "Belgium", ISO2 = "BE", ISO3 = "BEL", PhoneCode = "32", Continent = "Europe", Capital = "Brussels", TimeZone = "Europe/Brussels", Currency = "Euro", Language = "nl-BE,fr-BE,de-BE", LangDescrip = "Dutch (official) 60%, French (official) 40%, German (official) less than 1%, legally bilingual (Dutch and French)", Mobile = "12880000", LandLine = "4631000" });
            //countries.Add(new Country { Name = "Belize", ISO2 = "BZ", ISO3 = "BLZ", PhoneCode = "501", Continent = "North America", Capital = "Belmopan", TimeZone = "America/Belize", Currency = "Dollar", Language = "en-BZ,es", LangDescrip = "Spanish 46%, Creole 32.9%, Mayan dialects 8.9%, English 3.9% (official), Garifuna 3.4% (Carib), German 3.3%, other 1.4%, unknown 0.2% (2000 census)", Mobile = "164200", LandLine = "25400" });
            //countries.Add(new Country { Name = "Benin", ISO2 = "BJ", ISO3 = "BEN", PhoneCode = "229", Continent = "Africa", Capital = "Porto-Novo", TimeZone = "Africa/Porto-Novo", Currency = "Franc", Language = "fr-BJ", LangDescrip = "French (official), Fon and Yoruba (most common vernaculars in south), tribal languages (at least six major ones in north)", Mobile = "8408000", LandLine = "156700" });
            //countries.Add(new Country { Name = "Bermuda", ISO2 = "BM", ISO3 = "BMU", PhoneCode = "1-441", Continent = "North America", Capital = "Hamilton", TimeZone = "Atlantic/Bermuda", Currency = "Dollar", Language = "en-BM,pt", LangDescrip = "English (official), Portuguese", Mobile = "91000", LandLine = "69000" });
            //countries.Add(new Country { Name = "Bhutan", ISO2 = "BT", ISO3 = "BTN", PhoneCode = "975", Continent = "Asia", Capital = "Thimphu", TimeZone = "Asia/Thimphu", Currency = "Ngultrum", Language = "dz", LangDescrip = "Sharchhopka 28%, Dzongkha (official) 24%, Lhotshamkha 22%, other 26% (includes foreign languages) (2005 est.)", Mobile = "560000", LandLine = "27000" });
            //countries.Add(new Country { Name = "Bolivia", ISO2 = "BO", ISO3 = "BOL", PhoneCode = "591", Continent = "South America", Capital = "Sucre", TimeZone = "America/La_Paz", Currency = "Boliviano", Language = "es-BO,qu,ay", LangDescrip = "Spanish (official) 60.7%, Quechua (official) 21.2%, Aymara (official) 14.6%, Guarani (official), foreign languages 2.4%, other 1.2%", Mobile = "9494000", LandLine = "880600" });
            //countries.Add(new Country { Name = "Bosnia and Herzegovina", ISO2 = "BA", ISO3 = "BIH", PhoneCode = "387", Continent = "Europe", Capital = "Sarajevo", TimeZone = "Europe/Sarajevo", Currency = "Marka", Language = "bs,hr-BA,sr-BA", LangDescrip = "Bosnian (official), Croatian (official), Serbian (official)", Mobile = "3350000", LandLine = "878000" });
            //countries.Add(new Country { Name = "Botswana", ISO2 = "BW", ISO3 = "BWA", PhoneCode = "267", Continent = "Africa", Capital = "Gaborone", TimeZone = "Africa/Gaborone", Currency = "Pula", Language = "en-BW,tn-BW", LangDescrip = "Setswana 78.2%, Kalanga 7.9%, Sekgalagadi 2.8%, English (official) 2.1%, other 8.6%, unspecified 0.4% (2001 census)", Mobile = "3082000", LandLine = "160500" });
            //countries.Add(new Country { Name = "Brazil", ISO2 = "BR", ISO3 = "BRA", PhoneCode = "55", Continent = "South America", Capital = "Brasilia", TimeZone = "America/Sao_Paulo", Currency = "Real", Language = "pt-BR,es,en,fr", LangDescrip = "Portuguese (official and most widely spoken language)", Mobile = "248324000", LandLine = "44300000" });
            //countries.Add(new Country { Name = "British Indian Ocean Territory", ISO2 = "IO", ISO3 = "IOT", PhoneCode = "246", Continent = "Asia", Capital = "Diego Garcia", TimeZone = "Indian/Chagos", Currency = "Dollar", Language = "en-IO", LangDescrip = "English", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "British Virgin Islands", ISO2 = "VG", ISO3 = "VGB", PhoneCode = "1-284", Continent = "North America", Capital = "Road Town", TimeZone = "America/Tortola", Currency = "Dollar", Language = "en-VG", LangDescrip = "English (official)", Mobile = "48700", LandLine = "12268" });
            //countries.Add(new Country { Name = "Brunei", ISO2 = "BN", ISO3 = "BRN", PhoneCode = "673", Continent = "Asia", Capital = "Bandar Seri Begawan", TimeZone = "Asia/Brunei", Currency = "Dollar", Language = "ms-BN,en-BN", LangDescrip = "Malay (official), English, Chinese", Mobile = "469700", LandLine = "70933" });
            //countries.Add(new Country { Name = "Bulgaria", ISO2 = "BG", ISO3 = "BGR", PhoneCode = "359", Continent = "Europe", Capital = "Sofia", TimeZone = "Europe/Sofia", Currency = "Lev", Language = "bg,tr-BG", LangDescrip = "Bulgarian (official) 76.8%, Turkish 8.2%, Roma 3.8%, other 0.7%, unspecified 10.5% (2011 est.)", Mobile = "10780000", LandLine = "2253000" });
            //countries.Add(new Country { Name = "Burkina Faso", ISO2 = "BF", ISO3 = "BFA", PhoneCode = "226", Continent = "Africa", Capital = "Ouagadougou", TimeZone = "Africa/Ouagadougou", Currency = "Franc", Language = "fr-BF", LangDescrip = "French (official), native African languages belonging to Sudanic family spoken by 90% of the population", Mobile = "9980000", LandLine = "141400" });
            //countries.Add(new Country { Name = "Burundi", ISO2 = "BI", ISO3 = "BDI", PhoneCode = "257", Continent = "Africa", Capital = "Bujumbura", TimeZone = "Africa/Bujumbura", Currency = "Franc", Language = "fr-BI,rn", LangDescrip = "Kirundi 29.7% (official), Kirundi and other language 9.1%, French (official) and French and other language 0.3%, Swahili and Swahili and other language 0.2% (along Lake Tanganyika and in the Bujumbura area), English and English and other language 0.06%, more than 2 languages 3.7%, unspecified 56.9% (2008 est.)", Mobile = "2247000", LandLine = "17400" });
            //countries.Add(new Country { Name = "Cambodia", ISO2 = "KH", ISO3 = "KHM", PhoneCode = "855", Continent = "Asia", Capital = "Phnom Penh", TimeZone = "Asia/Phnom_Penh", Currency = "Riels", Language = "km,fr,en", LangDescrip = "Khmer (official) 96.3%, other 3.7% (2008 est.)", Mobile = "19100000", LandLine = "584000" });
            //countries.Add(new Country { Name = "Cameroon", ISO2 = "CM", ISO3 = "CMR", PhoneCode = "237", Continent = "Africa", Capital = "Yaounde", TimeZone = "Africa/Douala", Currency = "Franc", Language = "en-CM,fr-CM", LangDescrip = "24 major African language groups, English (official), French (official)", Mobile = "13100000", LandLine = "737400" });
            //countries.Add(new Country { Name = "Canada", ISO2 = "CA", ISO3 = "CAN", PhoneCode = "1", Continent = "North America", Capital = "Ottawa", TimeZone = "America/Toronto", Currency = "Dollar", Language = "en-CA,fr-CA,iu", LangDescrip = "English (official) 58.7%, French (official) 22%, Punjabi 1.4%, Italian 1.3%, Spanish 1.3%, German 1.3%, Cantonese 1.2%, Tagalog 1.2%, Arabic 1.1%, other 10.5% (2011 est.)", Mobile = "26263000", LandLine = "18010000" });
            //countries.Add(new Country { Name = "Cape Verde", ISO2 = "CV", ISO3 = "CPV", PhoneCode = "238", Continent = "Africa", Capital = "Praia", TimeZone = "Atlantic/Cape_Verde", Currency = "Escudo", Language = "pt-CV", LangDescrip = "Portuguese (official), Crioulo (a blend of Portuguese and West African words)", Mobile = "425300", LandLine = "70200" });
            //countries.Add(new Country { Name = "Cayman Islands", ISO2 = "KY", ISO3 = "CYM", PhoneCode = "1-345", Continent = "North America", Capital = "George Town", TimeZone = "America/Cayman", Currency = "Dollar", Language = "en-KY", LangDescrip = "English (official) 90.9%, Spanish 4%, Filipino 3.3%, other 1.7%, unspecified 0.1% (2010 est.)", Mobile = "96300", LandLine = "37400" });
            //countries.Add(new Country { Name = "Central African Republic", ISO2 = "CF", ISO3 = "CAF", PhoneCode = "236", Continent = "Africa", Capital = "Bangui", TimeZone = "Africa/Bangui", Currency = "Franc", Language = "fr-CF,sg,ln,kg", LangDescrip = "French (official), Sangho (lingua franca and national language), tribal languages", Mobile = "1070000", LandLine = "5600" });
            //countries.Add(new Country { Name = "Chad", ISO2 = "TD", ISO3 = "TCD", PhoneCode = "235", Continent = "Africa", Capital = "N'Djamena", TimeZone = "Africa/Ndjamena", Currency = "Franc", Language = "fr-TD,ar-TD,sre", LangDescrip = "French (official), Arabic (official), Sara (in south), more than 120 different languages and dialects", Mobile = "4200000", LandLine = "29900" });
            //countries.Add(new Country { Name = "Chile", ISO2 = "CL", ISO3 = "CHL", PhoneCode = "56", Continent = "South America", Capital = "Santiago", TimeZone = "America/Santiago", Currency = "Peso", Language = "es-CL", LangDescrip = "Spanish 99.5% (official), English 10.2%, indigenous 1% (includes Mapudungun, Aymara, Quechua, Rapa Nui), other 2.3%, unspecified 0.2%", Mobile = "24130000", LandLine = "3276000" });
            //countries.Add(new Country { Name = "China", ISO2 = "CN", ISO3 = "CHN", PhoneCode = "86", Continent = "Asia", Capital = "Beijing", TimeZone = "Asia/Shanghai", Currency = "Yuan Renminbi", Language = "zh-CN,yue,wuu,dta,ug,za", LangDescrip = "Standard Chinese or Mandarin (official; Putonghua, based on the Beijing dialect), Yue (Cantonese), Wu (Shanghainese), Minbei (Fuzhou), Minnan (Hokkien-Taiwanese), Xiang, Gan, Hakka dialects, minority languages", Mobile = "1100000000", LandLine = "278860000" });
            //countries.Add(new Country { Name = "Christmas Island", ISO2 = "CX", ISO3 = "CXR", PhoneCode = "61", Continent = "Asia", Capital = "Flying Fish Cove", TimeZone = "Indian/Christmas", Currency = "Dollar", Language = "en,zh,ms-CC", LangDescrip = "English (official), Chinese, Malay", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Cocos Islands", ISO2 = "CC", ISO3 = "CCK", PhoneCode = "61", Continent = "Asia", Capital = "West Island", TimeZone = "Indian/Cocos", Currency = "Dollar", Language = "ms-CC,en", LangDescrip = "Malay (Cocos dialect), English", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Colombia", ISO2 = "CO", ISO3 = "COL", PhoneCode = "57", Continent = "South America", Capital = "Bogota", TimeZone = "America/Bogota", Currency = "Peso", Language = "es-CO", LangDescrip = "Spanish (official)", Mobile = "49066000", LandLine = "6291000" });
            //countries.Add(new Country { Name = "Comoros", ISO2 = "KM", ISO3 = "COM", PhoneCode = "269", Continent = "Africa", Capital = "Moroni", TimeZone = "Indian/Comoro", Currency = "Franc", Language = "ar,fr-KM", LangDescrip = "Arabic (official), French (official), Shikomoro (a blend of Swahili and Arabic)", Mobile = "250000", LandLine = "24000" });
            //countries.Add(new Country { Name = "Cook Islands", ISO2 = "CK", ISO3 = "COK", PhoneCode = "682", Continent = "Oceania", Capital = "Avarua", TimeZone = "Pacific/Rarotonga", Currency = "Dollar", Language = "en-CK,mi", LangDescrip = "English (official) 86.4%, Cook Islands Maori (Rarotongan) (official) 76.2%, other 8.3%", Mobile = "7800", LandLine = "7200" });
            //countries.Add(new Country { Name = "Costa Rica", ISO2 = "CR", ISO3 = "CRI", PhoneCode = "506", Continent = "North America", Capital = "San Jose", TimeZone = "America/Costa_Rica", Currency = "Colon", Language = "es-CR,en", LangDescrip = "Spanish (official), English", Mobile = "6151000", LandLine = "1018000" });
            //countries.Add(new Country { Name = "Croatia", ISO2 = "HR", ISO3 = "HRV", PhoneCode = "385", Continent = "Europe", Capital = "Zagreb", TimeZone = "Europe/Zagreb", Currency = "Kuna", Language = "hr-HR,sr", LangDescrip = "Croatian (official) 95.6%, Serbian 1.2%, other 3% (including Hungarian, Czech, Slovak, and Albanian), unspecified 0.2% (2011 est.)", Mobile = "4970000", LandLine = "1640000" });
            //countries.Add(new Country { Name = "Cuba", ISO2 = "CU", ISO3 = "CUB", PhoneCode = "53", Continent = "North America", Capital = "Havana", TimeZone = "America/Havana", Currency = "Peso", Language = "es-CU", LangDescrip = "Spanish (official)", Mobile = "1682000", LandLine = "1217000" });
            //countries.Add(new Country { Name = "Curacao", ISO2 = "CW", ISO3 = "CUW", PhoneCode = "599", Continent = "North America", Capital = "Willemstad", TimeZone = "America/Curacao", Currency = "Guilder", Language = "nl,pap", LangDescrip = "Papiamentu (a Spanish-Portuguese-Dutch-English dialect) 81.2%, Dutch (official) 8%, Spanish 4%, English 2.9%, other 3.9% (2001 census)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Cyprus", ISO2 = "CY", ISO3 = "CYP", PhoneCode = "357", Continent = "Europe", Capital = "Nicosia", TimeZone = "Asia/Nicosia", Currency = "Euro", Language = "el-CY,tr-CY,en", LangDescrip = "Greek (official) 80.9%, Turkish (official) 0.2%, English 4.1%, Romanian 2.9%, Russian 2.5%, Bulgarian 2.2%, Arabic 1.2%, Filippino 1.1%, other 4.3%, unspecified 0.6% (2011 est.)", Mobile = "1110000", LandLine = "373200" });
            //countries.Add(new Country { Name = "Czech Republic", ISO2 = "CZ", ISO3 = "CZE", PhoneCode = "420", Continent = "Europe", Capital = "Prague", TimeZone = "Europe/Prague", Currency = "Koruna", Language = "cs,sk", LangDescrip = "Czech 95.4%, Slovak 1.6%, other 3% (2011 census)", Mobile = "12973000", LandLine = "2100000" });
            //countries.Add(new Country { Name = "Democratic Republic of the Congo", ISO2 = "CD", ISO3 = "COD", PhoneCode = "243", Continent = "Africa", Capital = "Kinshasa", TimeZone = "Africa/Kinshasa", Currency = "Franc", Language = "fr-CD,ln,kg", LangDescrip = "French (official), Lingala (a lingua franca trade language), Kingwana (a dialect of Kiswahili or Swahili), Kikongo, Tshiluba", Mobile = "19487000", LandLine = "58200" });
            //countries.Add(new Country { Name = "Denmark", ISO2 = "DK", ISO3 = "DNK", PhoneCode = "45", Continent = "Europe", Capital = "Copenhagen", TimeZone = "Europe/Copenhagen", Currency = "Krone", Language = "da-DK,en,fo,de-DK", LangDescrip = "Danish, Faroese, Greenlandic (an Inuit dialect), German (small minority)", Mobile = "6600000", LandLine = "2431000" });
            //countries.Add(new Country { Name = "Djibouti", ISO2 = "DJ", ISO3 = "DJI", PhoneCode = "253", Continent = "Africa", Capital = "Djibouti", TimeZone = "Africa/Djibouti", Currency = "Franc", Language = "fr-DJ,ar,so-DJ,aa", LangDescrip = "French (official), Arabic (official), Somali, Afar", Mobile = "209000", LandLine = "18000" });
            //countries.Add(new Country { Name = "Dominica", ISO2 = "DM", ISO3 = "DMA", PhoneCode = "1-767", Continent = "North America", Capital = "Roseau", TimeZone = "America/Dominica", Currency = "Dollar", Language = "en-DM", LangDescrip = "English (official), French patois", Mobile = "109300", LandLine = "14600" });
            //countries.Add(new Country { Name = "Dominican Republic", ISO2 = "DO", ISO3 = "DOM", PhoneCode = "1-809, 1-829, 1-849", Continent = "North America", Capital = "Santo Domingo", TimeZone = "America/Santo_Domingo", Currency = "Peso", Language = "es-DO", LangDescrip = "Spanish (official)", Mobile = "9038000", LandLine = "1065000" });
            //countries.Add(new Country { Name = "East Timor", ISO2 = "TL", ISO3 = "TLS", PhoneCode = "670", Continent = "Oceania", Capital = "Dili", TimeZone = "Asia/Dili", Currency = "Dollar", Language = "tet,pt-TL,id,en", LangDescrip = "Tetum (official), Portuguese (official), Indonesian, English", Mobile = "621000", LandLine = "3000" });
            //countries.Add(new Country { Name = "Ecuador", ISO2 = "EC", ISO3 = "ECU", PhoneCode = "593", Continent = "South America", Capital = "Quito", TimeZone = "America/Guayaquil", Currency = "Dollar", Language = "es-EC", LangDescrip = "Spanish (Castillian) 93% (official), Quechua 4.1%, other indigenous 0.7%, foreign 2.2%", Mobile = "16457000", LandLine = "2310000" });
            //countries.Add(new Country { Name = "Egypt", ISO2 = "EG", ISO3 = "EGY", PhoneCode = "20", Continent = "Africa", Capital = "Cairo", TimeZone = "Africa/Cairo", Currency = "Pound", Language = "ar-EG,en,fr", LangDescrip = "Arabic (official), English and French widely understood by educated classes", Mobile = "96800000", LandLine = "8557000" });
            //countries.Add(new Country { Name = "El Salvador", ISO2 = "SV", ISO3 = "SLV", PhoneCode = "503", Continent = "North America", Capital = "San Salvador", TimeZone = "America/El_Salvador", Currency = "Dollar", Language = "es-SV", LangDescrip = "Spanish (official), Nahua (among some Amerindians)", Mobile = "8650000", LandLine = "1060000" });
            //countries.Add(new Country { Name = "Equatorial Guinea", ISO2 = "GQ", ISO3 = "GNQ", PhoneCode = "240", Continent = "Africa", Capital = "Malabo", TimeZone = "Africa/Malabo", Currency = "Franc", Language = "es-GQ,fr", LangDescrip = "Spanish (official) 67.6%, other (includes French (official), Fang, Bubi) 32.4% (1994 census)", Mobile = "501000", LandLine = "14900" });
            //countries.Add(new Country { Name = "Eritrea", ISO2 = "ER", ISO3 = "ERI", PhoneCode = "291", Continent = "Africa", Capital = "Asmara", TimeZone = "Africa/Asmara", Currency = "Nakfa", Language = "aa-ER,ar,tig,kun,ti-ER", LangDescrip = "Tigrinya (official), Arabic (official), English (official), Tigre, Kunama, Afar, other Cushitic languages", Mobile = "305300", LandLine = "60000" });
            //countries.Add(new Country { Name = "Estonia", ISO2 = "EE", ISO3 = "EST", PhoneCode = "372", Continent = "Europe", Capital = "Tallinn", TimeZone = "Europe/Tallinn", Currency = "Euro", Language = "et,ru", LangDescrip = "Estonian (official) 68.5%, Russian 29.6%, Ukrainian 0.6%, other 1.2%, unspecified 0.1% (2011 est.)", Mobile = "2070000", LandLine = "448200" });
            //countries.Add(new Country { Name = "Ethiopia", ISO2 = "ET", ISO3 = "ETH", PhoneCode = "251", Continent = "Africa", Capital = "Addis Ababa", TimeZone = "Africa/Addis_Ababa", Currency = "Birr", Language = "am,en-ET,om-ET,ti-ET,so-ET,sid", LangDescrip = "Oromo (official working language in the State of Oromiya) 33.8%, Amharic (official national language) 29.3%, Somali (official working language of the State of Sumale) 6.2%, Tigrigna (Tigrinya) (official working language of the State of Tigray) 5.9%, Sidamo 4%, Wolaytta 2.2%, Gurage 2%, Afar (official working language of the State of Afar) 1.7%, Hadiyya 1.7%, Gamo 1.5%, Gedeo 1.3%, Opuuo 1.2%, Kafa 1.1%, other 8.1%, English (major foreign language taught in schools), Arabic (2007 est.)", Mobile = "20524000", LandLine = "797500" });
            //countries.Add(new Country { Name = "Falkland Islands", ISO2 = "FK", ISO3 = "FLK", PhoneCode = "500", Continent = "South America", Capital = "Stanley", TimeZone = "Atlantic/Stanley", Currency = "Pound", Language = "en-FK", LangDescrip = "English 89%, Spanish 7.7%, other 3.3% (2006 est.)", Mobile = "3450", LandLine = "1980" });
            //countries.Add(new Country { Name = "Faroe Islands", ISO2 = "FO", ISO3 = "FRO", PhoneCode = "298", Continent = "Europe", Capital = "Torshavn", TimeZone = "Atlantic/Faroe", Currency = "Krone", Language = "fo,da-FO", LangDescrip = "Faroese (derived from Old Norse), Danish", Mobile = "61000", LandLine = "24000" });
            //countries.Add(new Country { Name = "Fiji", ISO2 = "FJ", ISO3 = "FJI", PhoneCode = "679", Continent = "Oceania", Capital = "Suva", TimeZone = "Pacific/Fiji", Currency = "Dollar", Language = "en-FJ,fj", LangDescrip = "English (official), Fijian (official), Hindustani", Mobile = "858800", LandLine = "88400" });
            //countries.Add(new Country { Name = "Finland", ISO2 = "FI", ISO3 = "FIN", PhoneCode = "358", Continent = "Europe", Capital = "Helsinki", TimeZone = "Europe/Helsinki", Currency = "Euro", Language = "fi-FI,sv-FI,smn", LangDescrip = "Finnish (official) 94.2%, Swedish (official) 5.5%, other (small Sami- and Russian-speaking minorities) 0.2% (2012 est.)", Mobile = "9320000", LandLine = "890000" });
            //countries.Add(new Country { Name = "France", ISO2 = "FR", ISO3 = "FRA", PhoneCode = "33", Continent = "Europe", Capital = "Paris", TimeZone = "Europe/Paris", Currency = "Euro", Language = "fr-FR,frp,br,co,ca,eu,oc", LangDescrip = "French (official) 100%, rapidly declining regional dialects and languages (Provencal, Breton, Alsatian, Corsican, Catalan, Basque, Flemish)", Mobile = "62280000", LandLine = "39290000" });
            //countries.Add(new Country { Name = "French Polynesia", ISO2 = "PF", ISO3 = "PYF", PhoneCode = "689", Continent = "Oceania", Capital = "Papeete", TimeZone = "Pacific/Tahiti", Currency = "Franc", Language = "fr-PF,ty", LangDescrip = "French (official) 61.1%, Polynesian (official) 31.4%, Asian languages 1.2%, other 0.3%, unspecified 6% (2002 census)", Mobile = "226000", LandLine = "55000" });
            //countries.Add(new Country { Name = "Gabon", ISO2 = "GA", ISO3 = "GAB", PhoneCode = "241", Continent = "Africa", Capital = "Libreville", TimeZone = "Africa/Libreville", Currency = "Franc", Language = "fr-GA", LangDescrip = "French (official), Fang, Myene, Nzebi, Bapounou/Eschira, Bandjabi", Mobile = "2930000", LandLine = "17000" });
            //countries.Add(new Country { Name = "Gambia", ISO2 = "GM", ISO3 = "GMB", PhoneCode = "220", Continent = "Africa", Capital = "Banjul", TimeZone = "Africa/Banjul", Currency = "Dalasi", Language = "en-GM,mnk,wof,wo,ff", LangDescrip = "English (official), Mandinka, Wolof, Fula, other indigenous vernaculars", Mobile = "1526000", LandLine = "64200" });
            //countries.Add(new Country { Name = "Georgia", ISO2 = "GE", ISO3 = "GEO", PhoneCode = "995", Continent = "Asia", Capital = "Tbilisi", TimeZone = "Asia/Tbilisi", Currency = "Lari", Language = "ka,ru,hy,az", LangDescrip = "Georgian (official) 71%, Russian 9%, Armenian 7%, Azeri 6%, other 7%", Mobile = "4699000", LandLine = "1276000" });
            //countries.Add(new Country { Name = "Germany", ISO2 = "DE", ISO3 = "DEU", PhoneCode = "49", Continent = "Europe", Capital = "Berlin", TimeZone = "Europe/Berlin", Currency = "Euro", Language = "de", LangDescrip = "German (official)", Mobile = "107700000", LandLine = "50700000" });
            //countries.Add(new Country { Name = "Ghana", ISO2 = "GH", ISO3 = "GHA", PhoneCode = "233", Continent = "Africa", Capital = "Accra", TimeZone = "Africa/Accra", Currency = "Cedi", Language = "en-GH,ak,ee,tw", LangDescrip = "Asante 14.8%, Ewe 12.7%, Fante 9.9%, Boron (Brong) 4.6%, Dagomba 4.3%, Dangme 4.3%, Dagarte (Dagaba) 3.7%, Akyem 3.4%, Ga 3.4%, Akuapem 2.9%, other (includes English (official)) 36.1% (2000 census)", Mobile = "25618000", LandLine = "285000" });
            //countries.Add(new Country { Name = "Gibraltar", ISO2 = "GI", ISO3 = "GIB", PhoneCode = "350", Continent = "Europe", Capital = "Gibraltar", TimeZone = "Europe/Gibraltar", Currency = "Pound", Language = "en-GI,es,it,pt", LangDescrip = "English (used in schools and for official purposes), Spanish, Italian, Portuguese", Mobile = "34750", LandLine = "23100" });
            //countries.Add(new Country { Name = "Greece", ISO2 = "GR", ISO3 = "GRC", PhoneCode = "30", Continent = "Europe", Capital = "Athens", TimeZone = "Europe/Athens", Currency = "Euro", Language = "el-GR,en,fr", LangDescrip = "Greek (official) 99%, other (includes English and French) 1%", Mobile = "13354000", LandLine = "5461000" });
            //countries.Add(new Country { Name = "Greenland", ISO2 = "GL", ISO3 = "GRL", PhoneCode = "299", Continent = "North America", Capital = "Nuuk", TimeZone = "America/Godthab", Currency = "Krone", Language = "kl,da-GL,en", LangDescrip = "Greenlandic (East Inuit) (official), Danish (official), English", Mobile = "59455", LandLine = "18900" });
            //countries.Add(new Country { Name = "Grenada", ISO2 = "GD", ISO3 = "GRD", PhoneCode = "1-473", Continent = "North America", Capital = "St. George's", TimeZone = "America/Grenada", Currency = "Dollar", Language = "en-GD", LangDescrip = "English (official), French patois", Mobile = "128000", LandLine = "28500" });
            //countries.Add(new Country { Name = "Guam", ISO2 = "GU", ISO3 = "GUM", PhoneCode = "1-671", Continent = "Oceania", Capital = "Hagatna", TimeZone = "Pacific/Guam", Currency = "Dollar", Language = "en-GU,ch-GU", LangDescrip = "English 43.6%, Filipino 21.2%, Chamorro 17.8%, other Pacific island languages 10%, Asian languages 6.3%, other 1.1% (2010 est.)", Mobile = "98000", LandLine = "67000" });
            //countries.Add(new Country { Name = "Guatemala", ISO2 = "GT", ISO3 = "GTM", PhoneCode = "502", Continent = "North America", Capital = "Guatemala City", TimeZone = "America/Guatemala", Currency = "Quetzal", Language = "es-GT", LangDescrip = "Spanish (official) 60%, Amerindian languages 40%", Mobile = "20787000", LandLine = "1744000" });
            //countries.Add(new Country { Name = "Guernsey", ISO2 = "GG", ISO3 = "GGY", PhoneCode = "44-1481", Continent = "Europe", Capital = "St Peter Port", TimeZone = "Europe/Guernsey", Currency = "Pound", Language = "en,fr", LangDescrip = "English, French, Norman-French dialect spoken in country districts", Mobile = "43800", LandLine = "45100" });
            //countries.Add(new Country { Name = "Guinea", ISO2 = "GN", ISO3 = "GIN", PhoneCode = "224", Continent = "Africa", Capital = "Conakry", TimeZone = "Africa/Conakry", Currency = "Franc", Language = "fr-GN", LangDescrip = "French (official)", Mobile = "4781000", LandLine = "18000" });
            //countries.Add(new Country { Name = "Guinea-Bissau", ISO2 = "GW", ISO3 = "GNB", PhoneCode = "245", Continent = "Africa", Capital = "Bissau", TimeZone = "Africa/Bissau", Currency = "Franc", Language = "pt-GW,pov", LangDescrip = "Portuguese (official), Crioulo, African languages", Mobile = "1100000", LandLine = "5000" });
            //countries.Add(new Country { Name = "Guyana", ISO2 = "GY", ISO3 = "GUY", PhoneCode = "592", Continent = "South America", Capital = "Georgetown", TimeZone = "America/Guyana", Currency = "Dollar", Language = "en-GY", LangDescrip = "English, Amerindian dialects, Creole, Caribbean Hindustani (a dialect of Hindi), Urdu", Mobile = "547000", LandLine = "154200" });
            //countries.Add(new Country { Name = "Haiti", ISO2 = "HT", ISO3 = "HTI", PhoneCode = "509", Continent = "North America", Capital = "Port-au-Prince", TimeZone = "America/Port-au-Prince", Currency = "Gourde", Language = "ht,fr-HT", LangDescrip = "French (official), Creole (official)", Mobile = "6095000", LandLine = "50000" });
            //countries.Add(new Country { Name = "Honduras", ISO2 = "HN", ISO3 = "HND", PhoneCode = "504", Continent = "North America", Capital = "Tegucigalpa", TimeZone = "America/Tegucigalpa", Currency = "Lempira", Language = "es-HN", LangDescrip = "Spanish (official), Amerindian dialects", Mobile = "7370000", LandLine = "610000" });
            //countries.Add(new Country { Name = "Hong Kong", ISO2 = "HK", ISO3 = "HKG", PhoneCode = "852", Continent = "Asia", Capital = "Hong Kong", TimeZone = "Asia/Hong_Kong", Currency = "Dollar", Language = "zh-HK,yue,zh,en", LangDescrip = "Cantonese (official) 89.5%, English (official) 3.5%, Putonghua (Mandarin) 1.4%, other Chinese dialects 4%, other 1.6% (2011 est.)", Mobile = "16403000", LandLine = "4362000" });
            //countries.Add(new Country { Name = "Hungary", ISO2 = "HU", ISO3 = "HUN", PhoneCode = "36", Continent = "Europe", Capital = "Budapest", TimeZone = "Europe/Budapest", Currency = "Forint", Language = "hu-HU", LangDescrip = "Hungarian (official) 99.6%, English 16%, German 11.2%, Russian 1.6%, Romanian 1.3%, French 1.2%, other 4.2%", Mobile = "11580000", LandLine = "2960000" });
            //countries.Add(new Country { Name = "Iceland", ISO2 = "IS", ISO3 = "ISL", PhoneCode = "354", Continent = "Europe", Capital = "Reykjavik", TimeZone = "Atlantic/Reykjavik", Currency = "Krona", Language = "is,en,de,da,sv,no", LangDescrip = "Icelandic, English, Nordic languages, German widely spoken", Mobile = "346000", LandLine = "189000" });
            //countries.Add(new Country { Name = "India", ISO2 = "IN", ISO3 = "IND", PhoneCode = "91", Continent = "Asia", Capital = "New Delhi", TimeZone = "Asia/Kolkata", Currency = "Rupee", Language = "en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc", LangDescrip = "Hindi 41%, Bengali 8.1%, Telugu 7.2%, Marathi 7%, Tamil 5.9%, Urdu 5%, Gujarati 4.5%, Kannada 3.7%, Malayalam 3.2%, Oriya 3.2%, Punjabi 2.8%, Assamese 1.3%, Maithili 1.2%, other 5.9%", Mobile = "893862000", LandLine = "31080000" });
            //countries.Add(new Country { Name = "Indonesia", ISO2 = "ID", ISO3 = "IDN", PhoneCode = "62", Continent = "Asia", Capital = "Jakarta", TimeZone = "Asia/Jakarta", Currency = "Rupiah", Language = "id,en,nl,jv", LangDescrip = "Bahasa Indonesia (official, modified form of Malay), English, Dutch, local dialects (of which the most widely spoken is Javanese)", Mobile = "281960000", LandLine = "37983000" });
            //countries.Add(new Country { Name = "Iran", ISO2 = "IR", ISO3 = "IRN", PhoneCode = "98", Continent = "Asia", Capital = "Tehran", TimeZone = "Asia/Tehran", Currency = "Rial", Language = "fa-IR,ku", LangDescrip = "Persian (official) 53%, Azeri Turkic and Turkic dialects 18%, Kurdish 10%, Gilaki and Mazandarani 7%, Luri 6%, Balochi 2%, Arabic 2%, other 2%", Mobile = "58160000", LandLine = "28760000" });
            //countries.Add(new Country { Name = "Iraq", ISO2 = "IQ", ISO3 = "IRQ", PhoneCode = "964", Continent = "Asia", Capital = "Baghdad", TimeZone = "Asia/Baghdad", Currency = "Dinar", Language = "ar-IQ,ku,hy", LangDescrip = "Arabic (official), Kurdish (official), Turkmen (a Turkish dialect) and Assyrian (Neo-Aramaic) are official in areas where they constitute a majority of the population), Armenian", Mobile = "26760000", LandLine = "1870000" });
            //countries.Add(new Country { Name = "Ireland", ISO2 = "IE", ISO3 = "IRL", PhoneCode = "353", Continent = "Europe", Capital = "Dublin", TimeZone = "Europe/Dublin", Currency = "Euro", Language = "en-IE,ga-IE", LangDescrip = "English (official, the language generally used), Irish (Gaelic or Gaeilge) (official, spoken mainly in areas along the western coast)", Mobile = "4906000", LandLine = "2007000" });
            //countries.Add(new Country { Name = "Isle of Man", ISO2 = "IM", ISO3 = "IMN", PhoneCode = "44-1624", Continent = "Europe", Capital = "Douglas, Isle of Man", TimeZone = "Europe/Isle_of_Man", Currency = "Pound", Language = "en,gv", LangDescrip = "English, Manx Gaelic (about 2% of the population has some knowledge)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Israel", ISO2 = "IL", ISO3 = "ISR", PhoneCode = "972", Continent = "Asia", Capital = "Jerusalem", TimeZone = "Asia/Jerusalem", Currency = "Shekel", Language = "he,ar-IL,en-IL,", LangDescrip = "Hebrew (official), Arabic (used officially for Arab minority), English (most commonly used foreign language)", Mobile = "9225000", LandLine = "3594000" });
            //countries.Add(new Country { Name = "Italy", ISO2 = "IT", ISO3 = "ITA", PhoneCode = "39", Continent = "Europe", Capital = "Rome", TimeZone = "Europe/Rome", Currency = "Euro", Language = "it-IT,de-IT,fr-IT,sc,ca,co,sl", LangDescrip = "Italian (official), German (parts of Trentino-Alto Adige region are predominantly German-speaking), French (small French-speaking minority in Valle d'Aosta region), Slovene (Slovene-speaking minority in the Trieste-Gorizia area)", Mobile = "97225000", LandLine = "21656000" });
            //countries.Add(new Country { Name = "Ivory Coast", ISO2 = "CI", ISO3 = "CIV", PhoneCode = "225", Continent = "Africa", Capital = "Yamoussoukro", TimeZone = "Africa/Abidjan", Currency = "Franc", Language = "fr-CI", LangDescrip = "French (official), 60 native dialects of which Dioula is the most widely spoken", Mobile = "19827000", LandLine = "268000" });
            //countries.Add(new Country { Name = "Jamaica", ISO2 = "JM", ISO3 = "JAM", PhoneCode = "1-876", Continent = "North America", Capital = "Kingston", TimeZone = "America/Jamaica", Currency = "Dollar", Language = "en-JM", LangDescrip = "English, English patois", Mobile = "2665000", LandLine = "265000" });
            //countries.Add(new Country { Name = "Japan", ISO2 = "JP", ISO3 = "JPN", PhoneCode = "81", Continent = "Asia", Capital = "Tokyo", TimeZone = "Asia/Tokyo", Currency = "Yen", Language = "ja", LangDescrip = "Japanese", Mobile = "138363000", LandLine = "64273000" });
            //countries.Add(new Country { Name = "Jersey", ISO2 = "JE", ISO3 = "JEY", PhoneCode = "44-1534", Continent = "Europe", Capital = "Saint Helier", TimeZone = "Europe/Jersey", Currency = "Pound", Language = "en,pt", LangDescrip = "English 94.5% (official), Portuguese 4.6%, other 0.9% (2001 census)", Mobile = "108000", LandLine = "73800" });
            //countries.Add(new Country { Name = "Jordan", ISO2 = "JO", ISO3 = "JOR", PhoneCode = "962", Continent = "Asia", Capital = "Amman", TimeZone = "Asia/Amman", Currency = "Dinar", Language = "ar-JO,en", LangDescrip = "Arabic (official), English (widely understood among upper and middle classes)", Mobile = "8984000", LandLine = "435000" });
            //countries.Add(new Country { Name = "Kazakhstan", ISO2 = "KZ", ISO3 = "KAZ", PhoneCode = "7", Continent = "Asia", Capital = "Astana", TimeZone = "Asia/Almaty", Currency = "Tenge", Language = "kk,ru", LangDescrip = "Kazakh (official, Qazaq) 64.4%, Russian (official, used in everyday business, designated the language of interethnic communication) 95% (2001 est.)", Mobile = "28731000", LandLine = "4340000" });
            //countries.Add(new Country { Name = "Kenya", ISO2 = "KE", ISO3 = "KEN", PhoneCode = "254", Continent = "Africa", Capital = "Nairobi", TimeZone = "Africa/Nairobi", Currency = "Shilling", Language = "en-KE,sw-KE", LangDescrip = "English (official), Kiswahili (official), numerous indigenous languages", Mobile = "30732000", LandLine = "251600" });
            //countries.Add(new Country { Name = "Kiribati", ISO2 = "KI", ISO3 = "KIR", PhoneCode = "686", Continent = "Oceania", Capital = "Tarawa", TimeZone = "Pacific/Tarawa", Currency = "Dollar", Language = "en-KI,gil", LangDescrip = "I-Kiribati, English (official)", Mobile = "16000", LandLine = "9000" });
            //countries.Add(new Country { Name = "Kosovo", ISO2 = "XK", ISO3 = "XKX", PhoneCode = "383", Continent = "Europe", Capital = "Pristina", TimeZone = "Europe/Podgorica", Currency = "Euro", Language = "sq,sr", LangDescrip = "Albanian (official), Serbian (official), Bosnian, Turkish, Roma", Mobile = "562000", LandLine = "106300" });
            //countries.Add(new Country { Name = "Kuwait", ISO2 = "KW", ISO3 = "KWT", PhoneCode = "965", Continent = "Asia", Capital = "Kuwait City", TimeZone = "Asia/Kuwait", Currency = "Dinar", Language = "ar-KW,en", LangDescrip = "Arabic (official), English widely spoken", Mobile = "5526000", LandLine = "510000" });
            //countries.Add(new Country { Name = "Kyrgyzstan", ISO2 = "KG", ISO3 = "KGZ", PhoneCode = "996", Continent = "Asia", Capital = "Bishkek", TimeZone = "Asia/Bishkek", Currency = "Som", Language = "ky,uz,ru", LangDescrip = "Kyrgyz (official) 64.7%, Uzbek 13.6%, Russian (official) 12.5%, Dungun 1%, other 8.2% (1999 census)", Mobile = "6800000", LandLine = "489000" });
            //countries.Add(new Country { Name = "Laos", ISO2 = "LA", ISO3 = "LAO", PhoneCode = "856", Continent = "Asia", Capital = "Vientiane", TimeZone = "Asia/Vientiane", Currency = "Kip", Language = "lo,fr,en", LangDescrip = "Lao (official), French, English, various ethnic languages", Mobile = "6492000", LandLine = "112000" });
            //countries.Add(new Country { Name = "Latvia", ISO2 = "LV", ISO3 = "LVA", PhoneCode = "371", Continent = "Europe", Capital = "Riga", TimeZone = "Europe/Riga", Currency = "Euro", Language = "lv,ru,lt", LangDescrip = "Latvian (official) 56.3%, Russian 33.8%, other 0.6% (includes Polish, Ukrainian, and Belarusian), unspecified 9.4% (2011 est.)", Mobile = "2310000", LandLine = "501000" });
            //countries.Add(new Country { Name = "Lebanon", ISO2 = "LB", ISO3 = "LBN", PhoneCode = "961", Continent = "Asia", Capital = "Beirut", TimeZone = "Asia/Beirut", Currency = "Pound", Language = "ar-LB,fr-LB,en,hy", LangDescrip = "Arabic (official), French, English, Armenian", Mobile = "4000000", LandLine = "878000" });
            //countries.Add(new Country { Name = "Lesotho", ISO2 = "LS", ISO3 = "LSO", PhoneCode = "266", Continent = "Africa", Capital = "Maseru", TimeZone = "Africa/Maseru", Currency = "Loti", Language = "en-LS,st,zu,xh", LangDescrip = "Sesotho (official) (southern Sotho), English (official), Zulu, Xhosa", Mobile = "1312000", LandLine = "43100" });
            //countries.Add(new Country { Name = "Liberia", ISO2 = "LR", ISO3 = "LBR", PhoneCode = "231", Continent = "Africa", Capital = "Monrovia", TimeZone = "Africa/Monrovia", Currency = "Dollar", Language = "en-LR", LangDescrip = "English 20% (official), some 20 ethnic group languages few of which can be written or used in correspondence", Mobile = "2394000", LandLine = "3200" });
            //countries.Add(new Country { Name = "Libya", ISO2 = "LY", ISO3 = "LBY", PhoneCode = "218", Continent = "Africa", Capital = "Tripolis", TimeZone = "Africa/Tripoli", Currency = "Dinar", Language = "ar-LY,it,en", LangDescrip = "Arabic (official), Italian, English (all widely understood in the major cities); Berber (Nafusi, Ghadamis, Suknah, Awjilah, Tamasheq)", Mobile = "9590000", LandLine = "814000" });
            //countries.Add(new Country { Name = "Liechtenstein", ISO2 = "LI", ISO3 = "LIE", PhoneCode = "423", Continent = "Europe", Capital = "Vaduz", TimeZone = "Europe/Vaduz", Currency = "Franc", Language = "de-LI", LangDescrip = "German 94.5% (official) (Alemannic is the main dialect), Italian 1.1%, other 4.3% (2010 est.)", Mobile = "38000", LandLine = "20000" });
            //countries.Add(new Country { Name = "Lithuania", ISO2 = "LT", ISO3 = "LTU", PhoneCode = "370", Continent = "Europe", Capital = "Vilnius", TimeZone = "Europe/Vilnius", Currency = "Euro", Language = "lt,ru,pl", LangDescrip = "Lithuanian (official) 82%, Russian 8%, Polish 5.6%, other 0.9%, unspecified 3.5% (2011 est.)", Mobile = "5000000", LandLine = "667300" });
            //countries.Add(new Country { Name = "Luxembourg", ISO2 = "LU", ISO3 = "LUX", PhoneCode = "352", Continent = "Europe", Capital = "Luxembourg", TimeZone = "Europe/Luxembourg", Currency = "Euro", Language = "lb,de-LU,fr-LU", LangDescrip = "Luxembourgish (official administrative language and national language (spoken vernacular)), French (official administrative language), German (official administrative language)", Mobile = "761300", LandLine = "266700" });
            //countries.Add(new Country { Name = "Macau", ISO2 = "MO", ISO3 = "MAC", PhoneCode = "853", Continent = "Asia", Capital = "Macao", TimeZone = "Asia/Macau", Currency = "Pataca", Language = "zh,zh-MO,pt", LangDescrip = "Cantonese 83.3%, Mandarin 5%, Hokkien 3.7%, English 2.3%, other Chinese dialects 2%, Tagalog 1.7%, Portuguese 0.7%, other 1.3%", Mobile = "1613000", LandLine = "162500" });
            //countries.Add(new Country { Name = "Macedonia", ISO2 = "MK", ISO3 = "MKD", PhoneCode = "389", Continent = "Europe", Capital = "Skopje", TimeZone = "Europe/Skopje", Currency = "Denar", Language = "mk,sq,tr,rmm,sr", LangDescrip = "Macedonian (official) 66.5%, Albanian (official) 25.1%, Turkish 3.5%, Roma 1.9%, Serbian 1.2%, other 1.8% (2002 census)", Mobile = "2235000", LandLine = "407900" });
            //countries.Add(new Country { Name = "Madagascar", ISO2 = "MG", ISO3 = "MDG", PhoneCode = "261", Continent = "Africa", Capital = "Antananarivo", TimeZone = "Indian/Antananarivo", Currency = "Ariary", Language = "fr-MG,mg", LangDescrip = "French (official), Malagasy (official), English", Mobile = "8564000", LandLine = "143700" });
            //countries.Add(new Country { Name = "Malawi", ISO2 = "MW", ISO3 = "MWI", PhoneCode = "265", Continent = "Africa", Capital = "Lilongwe", TimeZone = "Africa/Blantyre", Currency = "Kwacha", Language = "ny,yao,tum,swk", LangDescrip = "English (official), Chichewa (common), Chinyanja, Chiyao, Chitumbuka, Chilomwe, Chinkhonde, Chingoni, Chisena, Chitonga, Chinyakyusa, Chilambya", Mobile = "4420000", LandLine = "227300" });
            //countries.Add(new Country { Name = "Malaysia", ISO2 = "MY", ISO3 = "MYS", PhoneCode = "60", Continent = "Asia", Capital = "Kuala Lumpur", TimeZone = "Asia/Kuala_Lumpur", Currency = "Ringgit", Language = "ms-MY,en,zh,ta,te,ml,pa,th", LangDescrip = "Bahasa Malaysia (official), English, Chinese (Cantonese, Mandarin, Hokkien, Hakka, Hainan, Foochow), Tamil, Telugu, Malayalam, Panjabi, Thai", Mobile = "41325000", LandLine = "4589000" });
            //countries.Add(new Country { Name = "Maldives", ISO2 = "MV", ISO3 = "MDV", PhoneCode = "960", Continent = "Asia", Capital = "Male", TimeZone = "Indian/Maldives", Currency = "Rufiyaa", Language = "dv,en", LangDescrip = "Dhivehi (official, dialect of Sinhala, script derived from Arabic), English (spoken by most government officials)", Mobile = "560000", LandLine = "23140" });
            //countries.Add(new Country { Name = "Mali", ISO2 = "ML", ISO3 = "MLI", PhoneCode = "223", Continent = "Africa", Capital = "Bamako", TimeZone = "Africa/Bamako", Currency = "Franc", Language = "fr-ML,bm", LangDescrip = "French (official), Bambara 46.3%, Peul/foulfoulbe 9.4%, Dogon 7.2%, Maraka/soninke 6.4%, Malinke 5.6%, Sonrhai/djerma 5.6%, Minianka 4.3%, Tamacheq 3.5%, Senoufo 2.6%, unspecified 0.6%, other 8.5%", Mobile = "14613000", LandLine = "112000" });
            //countries.Add(new Country { Name = "Malta", ISO2 = "MT", ISO3 = "MLT", PhoneCode = "356", Continent = "Europe", Capital = "Valletta", TimeZone = "Europe/Malta", Currency = "Euro", Language = "mt,en-MT", LangDescrip = "Maltese (official) 90.1%, English (official) 6%, multilingual 3%, other 0.9% (2005 est.)", Mobile = "539500", LandLine = "229700" });
            //countries.Add(new Country { Name = "Marshall Islands", ISO2 = "MH", ISO3 = "MHL", PhoneCode = "692", Continent = "Oceania", Capital = "Majuro", TimeZone = "Pacific/Majuro", Currency = "Dollar", Language = "mh,en-MH", LangDescrip = "Marshallese (official) 98.2%, other languages 1.8% (1999 census)", Mobile = "3800", LandLine = "4400" });
            //countries.Add(new Country { Name = "Mauritania", ISO2 = "MR", ISO3 = "MRT", PhoneCode = "222", Continent = "Africa", Capital = "Nouakchott", TimeZone = "Africa/Nouakchott", Currency = "Ouguiya", Language = "ar-MR,fuc,snk,fr,mey,wo", LangDescrip = "Arabic (official and national), Pulaar, Soninke, Wolof (all national languages), French, Hassaniya (a variety of Arabic)", Mobile = "4024000", LandLine = "65100" });
            //countries.Add(new Country { Name = "Mauritius", ISO2 = "MU", ISO3 = "MUS", PhoneCode = "230", Continent = "Africa", Capital = "Port Louis", TimeZone = "Indian/Mauritius", Currency = "Rupee", Language = "en-MU,bho,fr", LangDescrip = "Creole 86.5%, Bhojpuri 5.3%, French 4.1%, two languages 1.4%, other 2.6% (includes English, the official language, which is spoken by less than 1% of the population), unspecified 0.1% (2011 est.)", Mobile = "1485000", LandLine = "349100" });
            //countries.Add(new Country { Name = "Mayotte", ISO2 = "YT", ISO3 = "MYT", PhoneCode = "262", Continent = "Africa", Capital = "Mamoudzou", TimeZone = "Indian/Mayotte", Currency = "Euro", Language = "fr-YT", LangDescrip = "French", Mobile = "", LandLine = "" });
            countries.Add(new Country { Name = "Mexico", ISO2 = "MX", ISO3 = "MEX", PhoneCode = "52", Continent = "North America", Capital = "Mexico City", TimeZone = "America/Mexico_City", Currency = "Peso", Language = "es-MX", LangDescrip = "Spanish only 92.7%, Spanish and indigenous languages 5.7%, indigenous only 0.8%, unspecified 0.8%", Mobile = "100786000", LandLine = "20220000" });
            //countries.Add(new Country { Name = "Micronesia", ISO2 = "FM", ISO3 = "FSM", PhoneCode = "691", Continent = "Oceania", Capital = "Palikir", TimeZone = "Pacific/Pohnpei", Currency = "Dollar", Language = "en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg", LangDescrip = "English (official and common language), Chuukese, Kosrean, Pohnpeian, Yapese, Ulithian, Woleaian, Nukuoro, Kapingamarangi", Mobile = "27600", LandLine = "8400" });
            //countries.Add(new Country { Name = "Moldova", ISO2 = "MD", ISO3 = "MDA", PhoneCode = "373", Continent = "Europe", Capital = "Chisinau", TimeZone = "Europe/Chisinau", Currency = "Leu", Language = "ro,ru,gag,tr", LangDescrip = "Moldovan 58.8% (official; virtually the same as the Romanian language), Romanian 16.4%, Russian 16%, Ukrainian 3.8%, Gagauz 3.1% (a Turkish language), Bulgarian 1.1%, other 0.3%, unspecified 0.4%", Mobile = "4080000", LandLine = "1206000" });
            //countries.Add(new Country { Name = "Monaco", ISO2 = "MC", ISO3 = "MCO", PhoneCode = "377", Continent = "Europe", Capital = "Monaco", TimeZone = "Europe/Monaco", Currency = "Euro", Language = "fr-MC,en,it", LangDescrip = "French (official), English, Italian, Monegasque", Mobile = "33200", LandLine = "44500" });
            //countries.Add(new Country { Name = "Mongolia", ISO2 = "MN", ISO3 = "MNG", PhoneCode = "976", Continent = "Asia", Capital = "Ulan Bator", TimeZone = "Asia/Ulaanbaatar", Currency = "Tugrik", Language = "mn,ru", LangDescrip = "Khalkha Mongol 90% (official), Turkic, Russian (1999)", Mobile = "3375000", LandLine = "176700" });
            //countries.Add(new Country { Name = "Montenegro", ISO2 = "ME", ISO3 = "MNE", PhoneCode = "382", Continent = "Europe", Capital = "Podgorica", TimeZone = "Europe/Podgorica", Currency = "Euro", Language = "sr,hu,bs,sq,hr,rom", LangDescrip = "Serbian 42.9%, Montenegrin (official) 37%, Bosnian 5.3%, Albanian 5.3%, Serbo-Croat 2%, other 3.5%, unspecified 4% (2011 est.)", Mobile = "1126000", LandLine = "163000" });
            //countries.Add(new Country { Name = "Montserrat", ISO2 = "MS", ISO3 = "MSR", PhoneCode = "1-664", Continent = "North America", Capital = "Plymouth", TimeZone = "America/Montserrat", Currency = "Dollar", Language = "en-MS", LangDescrip = "English", Mobile = "4000", LandLine = "3000" });
            //countries.Add(new Country { Name = "Morocco", ISO2 = "MA", ISO3 = "MAR", PhoneCode = "212", Continent = "Africa", Capital = "Rabat", TimeZone = "Africa/Casablanca", Currency = "Dirham", Language = "ar-MA,fr", LangDescrip = "Arabic (official), Berber languages (Tamazight (official), Tachelhit, Tarifit), French (often the language of business, government, and diplomacy)", Mobile = "39016000", LandLine = "3280000" });
            //countries.Add(new Country { Name = "Mozambique", ISO2 = "MZ", ISO3 = "MOZ", PhoneCode = "258", Continent = "Africa", Capital = "Maputo", TimeZone = "Africa/Maputo", Currency = "Metical", Language = "pt-MZ,vmw", LangDescrip = "Emakhuwa 25.3%, Portuguese (official) 10.7%, Xichangana 10.3%, Cisena 7.5%, Elomwe 7%, Echuwabo 5.1%, other Mozambican languages 30.1%, other 4% (1997 census)", Mobile = "8108000", LandLine = "88100" });
            //countries.Add(new Country { Name = "Myanmar", ISO2 = "MM", ISO3 = "MMR", PhoneCode = "95", Continent = "Asia", Capital = "Nay Pyi Taw", TimeZone = "Asia/Rangoon", Currency = "Kyat", Language = "my", LangDescrip = "Burmese (official)", Mobile = "5440000", LandLine = "556000" });
            //countries.Add(new Country { Name = "Namibia", ISO2 = "NA", ISO3 = "NAM", PhoneCode = "264", Continent = "Africa", Capital = "Windhoek", TimeZone = "Africa/Windhoek", Currency = "Dollar", Language = "en-NA,af,de,hz,naq", LangDescrip = "Oshiwambo languages 48.9%, Nama/Damara 11.3%, Afrikaans 10.4% (common language of most of the population and about 60% of the white population), Otjiherero languages 8.6%, Kavango languages 8.5%, Caprivi languages 4.8%, English (official) 3.4%, other African languages 2.3%, other 1.7%", Mobile = "2435000", LandLine = "171000" });
            //countries.Add(new Country { Name = "Nauru", ISO2 = "NR", ISO3 = "NRU", PhoneCode = "674", Continent = "Oceania", Capital = "Yaren", TimeZone = "Pacific/Nauru", Currency = "Dollar", Language = "na,en-NR", LangDescrip = "Nauruan 93% (official, a distinct Pacific Island language), English 2% (widely understood, spoken, and used for most government and commercial purposes), other 5% (includes I-Kiribati 2% and Chinese 2%)", Mobile = "6800", LandLine = "1900" });
            //countries.Add(new Country { Name = "Nepal", ISO2 = "NP", ISO3 = "NPL", PhoneCode = "977", Continent = "Asia", Capital = "Kathmandu", TimeZone = "Asia/Kathmandu", Currency = "Rupee", Language = "ne,en", LangDescrip = "Nepali (official) 44.6%, Maithali 11.7%, Bhojpuri 6%, Tharu 5.8%, Tamang 5.1%, Newar 3.2%, Magar 3%, Bajjika 3%, Urdu 2.6%, Avadhi 1.9%, Limbu 1.3%, Gurung 1.2%, other 10.4%, unspecified 0.2%", Mobile = "18138000", LandLine = "834000" });
            //countries.Add(new Country { Name = "Netherlands", ISO2 = "NL", ISO3 = "NLD", PhoneCode = "31", Continent = "Europe", Capital = "Amsterdam", TimeZone = "Europe/Amsterdam", Currency = "Euro", Language = "nl-NL,fy-NL", LangDescrip = "Dutch (official)", Mobile = "19643000", LandLine = "7086000" });
            //countries.Add(new Country { Name = "Netherlands Antilles", ISO2 = "AN", ISO3 = "ANT", PhoneCode = "599", Continent = "North America", Capital = "Willemstad", TimeZone = "America/Curacao", Currency = "Guilder", Language = "nl-AN,en,es", LangDescrip = "Dutch, English, Spanish", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "New Caledonia", ISO2 = "NC", ISO3 = "NCL", PhoneCode = "687", Continent = "Oceania", Capital = "Noumea", TimeZone = "Pacific/Noumea", Currency = "Franc", Language = "fr-NC", LangDescrip = "French (official), 33 Melanesian-Polynesian dialects", Mobile = "231000", LandLine = "80000" });
            //countries.Add(new Country { Name = "New Zealand", ISO2 = "NZ", ISO3 = "NZL", PhoneCode = "64", Continent = "Oceania", Capital = "Wellington", TimeZone = "Pacific/Auckland", Currency = "Dollar", Language = "en-NZ,mi", LangDescrip = "English (de facto official) 89.8%, Maori (de jure official) 3.5%, Samoan 2%, Hindi 1.6%, French 1.2%, Northern Chinese 1.2%, Yue 1%, Other or not stated 20.5%, New Zealand Sign Language (de jure official)", Mobile = "4922000", LandLine = "1880000" });
            //countries.Add(new Country { Name = "Nicaragua", ISO2 = "NI", ISO3 = "NIC", PhoneCode = "505", Continent = "North America", Capital = "Managua", TimeZone = "America/Managua", Currency = "Cordoba", Language = "es-NI,en", LangDescrip = "Spanish (official) 95.3%, Miskito 2.2%, Mestizo of the Caribbean coast 2%, other 0.5%", Mobile = "5346000", LandLine = "320000" });
            //countries.Add(new Country { Name = "Niger", ISO2 = "NE", ISO3 = "NER", PhoneCode = "227", Continent = "Africa", Capital = "Niamey", TimeZone = "Africa/Niamey", Currency = "Franc", Language = "fr-NE,ha,kr,dje", LangDescrip = "French (official), Hausa, Djerma", Mobile = "5400000", LandLine = "100500" });
            //countries.Add(new Country { Name = "Nigeria", ISO2 = "NG", ISO3 = "NGA", PhoneCode = "234", Continent = "Africa", Capital = "Abuja", TimeZone = "Africa/Lagos", Currency = "Naira", Language = "en-NG,ha,yo,ig,ff", LangDescrip = "English (official), Hausa, Yoruba, Igbo (Ibo), Fulani, over 500 additional indigenous languages", Mobile = "112780000", LandLine = "418200" });
            //countries.Add(new Country { Name = "Niue", ISO2 = "NU", ISO3 = "NIU", PhoneCode = "683", Continent = "Oceania", Capital = "Alofi", TimeZone = "Pacific/Niue", Currency = "Dollar", Language = "niu,en-NU", LangDescrip = "Niuean (official) 46% (a Polynesian language closely related to Tongan and Samoan), Niuean and English 32%, English (official) 11%, Niuean and others 5%, other 6% (2011 est.)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "North Korea", ISO2 = "KP", ISO3 = "PRK", PhoneCode = "850", Continent = "Asia", Capital = "Pyongyang", TimeZone = "Asia/Pyongyang", Currency = "Won", Language = "ko-KP", LangDescrip = "Korean", Mobile = "1700000", LandLine = "1180000" });
            //countries.Add(new Country { Name = "Northern Mariana Islands", ISO2 = "MP", ISO3 = "MNP", PhoneCode = "1-670", Continent = "Oceania", Capital = "Saipan", TimeZone = "Pacific/Saipan", Currency = "Dollar", Language = "fil,tl,zh,ch-MP,en-MP", LangDescrip = "Philippine languages 32.8%, Chamorro (official) 24.1%, English (official) 17%, other Pacific island languages 10.1%, Chinese 6.8%, other Asian languages 7.3%, other 1.9% (2010 est.)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Norway", ISO2 = "NO", ISO3 = "NOR", PhoneCode = "47", Continent = "Europe", Capital = "Oslo", TimeZone = "Europe/Oslo", Currency = "Krone", Language = "no,nb,nn,se,fi", LangDescrip = "Bokmal Norwegian (official), Nynorsk Norwegian (official), small Sami- and Finnish-speaking minorities", Mobile = "5732000", LandLine = "1465000" });
            //countries.Add(new Country { Name = "Oman", ISO2 = "OM", ISO3 = "OMN", PhoneCode = "968", Continent = "Asia", Capital = "Muscat", TimeZone = "Asia/Muscat", Currency = "Rial", Language = "ar-OM,en,bal,ur", LangDescrip = "Arabic (official), English, Baluchi, Urdu, Indian dialects", Mobile = "5278000", LandLine = "305000" });
            //countries.Add(new Country { Name = "Pakistan", ISO2 = "PK", ISO3 = "PAK", PhoneCode = "92", Continent = "Asia", Capital = "Islamabad", TimeZone = "Asia/Karachi", Currency = "Rupee", Language = "ur-PK,en-PK,pa,sd,ps,brh", LangDescrip = "Punjabi 48%, Sindhi 12%, Saraiki (a Punjabi variant) 10%, Pashto (alternate name, Pashtu) 8%, Urdu (official) 8%, Balochi 3%, Hindko 2%, Brahui 1%, English (official; lingua franca of Pakistani elite and most government ministries), Burushaski, and other 8%", Mobile = "125000000", LandLine = "5803000" });
            //countries.Add(new Country { Name = "Palau", ISO2 = "PW", ISO3 = "PLW", PhoneCode = "680", Continent = "Oceania", Capital = "Melekeok", TimeZone = "Pacific/Palau", Currency = "Dollar", Language = "pau,sov,en-PW,tox,ja,fil,zh", LangDescrip = "Palauan (official on most islands) 66.6%, Carolinian 0.7%, other Micronesian 0.7%, English (official) 15.5%, Filipino 10.8%, Chinese 1.8%, other Asian 2.6%, other 1.3%", Mobile = "17150", LandLine = "7300" });
            //countries.Add(new Country { Name = "Palestine", ISO2 = "PS", ISO3 = "PSE", PhoneCode = "970", Continent = "Asia", Capital = "East Jerusalem", TimeZone = "Asia/Hebron", Currency = "Shekel", Language = "ar-PS", LangDescrip = "Arabic, Hebrew, English", Mobile = "3041000", LandLine = "406000" });
            //countries.Add(new Country { Name = "Panama", ISO2 = "PA", ISO3 = "PAN", PhoneCode = "507", Continent = "North America", Capital = "Panama City", TimeZone = "America/Panama", Currency = "Balboa", Language = "es-PA,en", LangDescrip = "Spanish (official), English 14%", Mobile = "6770000", LandLine = "640000" });
            //countries.Add(new Country { Name = "Papua New Guinea", ISO2 = "PG", ISO3 = "PNG", PhoneCode = "675", Continent = "Oceania", Capital = "Port Moresby", TimeZone = "Pacific/Port_Moresby", Currency = "Kina", Language = "en-PG,ho,meu,tpi", LangDescrip = "Tok Pisin (official), English (official), Hiri Motu (official), some 836 indigenous languages spoken (about 12% of the world's total); most languages have fewer than 1,000 speakers", Mobile = "2709000", LandLine = "139000" });
            //countries.Add(new Country { Name = "Paraguay", ISO2 = "PY", ISO3 = "PRY", PhoneCode = "595", Continent = "South America", Capital = "Asuncion", TimeZone = "America/Asuncion", Currency = "Guarani", Language = "es-PY,gn", LangDescrip = "Spanish (official), Guarani (official)", Mobile = "6790000", LandLine = "376000" });
            //countries.Add(new Country { Name = "Peru", ISO2 = "PE", ISO3 = "PER", PhoneCode = "51", Continent = "South America", Capital = "Lima", TimeZone = "America/Lima", Currency = "Sol", Language = "es-PE,qu,ay", LangDescrip = "Spanish (official) 84.1%, Quechua (official) 13%, Aymara (official) 1.7%, Ashaninka 0.3%, other native languages (includes a large number of minor Amazonian languages) 0.7%, other (includes foreign languages and sign language) 0.2% (2007 est.)", Mobile = "29400000", LandLine = "3420000" });
            //countries.Add(new Country { Name = "Philippines", ISO2 = "PH", ISO3 = "PHL", PhoneCode = "63", Continent = "Asia", Capital = "Manila", TimeZone = "Asia/Manila", Currency = "Peso", Language = "tl,en-PH,fil", LangDescrip = "Filipino (official; based on Tagalog) and English (official); eight major dialects - Tagalog, Cebuano, Ilocano, Hiligaynon or Ilonggo, Bicol, Waray, Pampango, and Pangasinan", Mobile = "103000000", LandLine = "3939000" });
            //countries.Add(new Country { Name = "Pitcairn", ISO2 = "PN", ISO3 = "PCN", PhoneCode = "64", Continent = "Oceania", Capital = "Adamstown", TimeZone = "Pacific/Pitcairn", Currency = "Dollar", Language = "en-PN", LangDescrip = "English", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Poland", ISO2 = "PL", ISO3 = "POL", PhoneCode = "48", Continent = "Europe", Capital = "Warsaw", TimeZone = "Europe/Warsaw", Currency = "Zloty", Language = "pl", LangDescrip = "Polish (official) 96.2%, Polish and non-Polish 2%, non-Polish 0.5%, unspecified 1.3%", Mobile = "50840000", LandLine = "6125000" });
            //countries.Add(new Country { Name = "Portugal", ISO2 = "PT", ISO3 = "PRT", PhoneCode = "351", Continent = "Europe", Capital = "Lisbon", TimeZone = "Europe/Lisbon", Currency = "Euro", Language = "pt-PT,mwl", LangDescrip = "Portuguese (official), Mirandese (official, but locally used)", Mobile = "12312000", LandLine = "4558000" });
            //countries.Add(new Country { Name = "Puerto Rico", ISO2 = "PR", ISO3 = "PRI", PhoneCode = "1-787, 1-939", Continent = "North America", Capital = "San Juan", TimeZone = "America/Puerto_Rico", Currency = "Dollar", Language = "en-PR,es-PR", LangDescrip = "Spanish, English", Mobile = "3060000", LandLine = "780200" });
            //countries.Add(new Country { Name = "Qatar", ISO2 = "QA", ISO3 = "QAT", PhoneCode = "974", Continent = "Asia", Capital = "Doha", TimeZone = "Asia/Qatar", Currency = "Rial", Language = "ar-QA,es", LangDescrip = "Arabic (official), English commonly used as a second language", Mobile = "2600000", LandLine = "327000" });
            //countries.Add(new Country { Name = "Republic of the Congo", ISO2 = "CG", ISO3 = "COG", PhoneCode = "242", Continent = "Africa", Capital = "Brazzaville", TimeZone = "Africa/Brazzaville", Currency = "Franc", Language = "fr-CG,kg,ln-CG", LangDescrip = "French (official), Lingala and Monokutuba (lingua franca trade languages), many local languages and dialects (of which Kikongo is the most widespread)", Mobile = "4283000", LandLine = "14900" });
            //countries.Add(new Country { Name = "Reunion", ISO2 = "RE", ISO3 = "REU", PhoneCode = "262", Continent = "Africa", Capital = "Saint-Denis", TimeZone = "Indian/Reunion", Currency = "Euro", Language = "fr-RE", LangDescrip = "French", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Romania", ISO2 = "RO", ISO3 = "ROU", PhoneCode = "40", Continent = "Europe", Capital = "Bucharest", TimeZone = "Europe/Bucharest", Currency = "Leu", Language = "ro,hu,rom", LangDescrip = "Romanian (official) 85.4%, Hungarian 6.3%, Romany (Gypsy) 1.2%, other 1%, unspecified 6.1% (2011 est.)", Mobile = "22700000", LandLine = "4680000" });
            //countries.Add(new Country { Name = "Russia", ISO2 = "RU", ISO3 = "RUS", PhoneCode = "7", Continent = "Europe", Capital = "Moscow", TimeZone = "Europe/Moscow", Currency = "Ruble", Language = "ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,tut,kbd,krc,ava,sah,nog", LangDescrip = "Russian (official) 96.3%, Dolgang 5.3%, German 1.5%, Chechen 1%, Tatar 3%, other 10.3%", Mobile = "261900000", LandLine = "42900000" });
            //countries.Add(new Country { Name = "Rwanda", ISO2 = "RW", ISO3 = "RWA", PhoneCode = "250", Continent = "Africa", Capital = "Kigali", TimeZone = "Africa/Kigali", Currency = "Franc", Language = "rw,en-RW,fr-RW,sw", LangDescrip = "Kinyarwanda only (official, universal Bantu vernacular) 93.2%, Kinyarwanda and other language(s) 6.2%, French (official) and other language(s) 0.1%, English (official) and other language(s) 0.1%, Swahili (or Kiswahili, used in commercial centers) 0.02%, other 0.03%, unspecified 0.3% (2002 est.)", Mobile = "5690000", LandLine = "44400" });
            //countries.Add(new Country { Name = "Saint Barthelemy", ISO2 = "BL", ISO3 = "BLM", PhoneCode = "590", Continent = "North America", Capital = "Gustavia", TimeZone = "America/St_Barthelemy", Currency = "Euro", Language = "fr", LangDescrip = "French (primary), English", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Saint Helena", ISO2 = "SH", ISO3 = "SHN", PhoneCode = "290", Continent = "Africa", Capital = "Jamestown", TimeZone = "Atlantic/St_Helena", Currency = "Pound", Language = "en-SH", LangDescrip = "English", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Saint Kitts and Nevis", ISO2 = "KN", ISO3 = "KNA", PhoneCode = "1-869", Continent = "North America", Capital = "Basseterre", TimeZone = "America/St_Kitts", Currency = "Dollar", Language = "en-KN", LangDescrip = "English (official)", Mobile = "84000", LandLine = "20000" });
            //countries.Add(new Country { Name = "Saint Lucia", ISO2 = "LC", ISO3 = "LCA", PhoneCode = "1-758", Continent = "North America", Capital = "Castries", TimeZone = "America/St_Lucia", Currency = "Dollar", Language = "en-LC", LangDescrip = "English (official), French patois", Mobile = "227000", LandLine = "36800" });
            //countries.Add(new Country { Name = "Saint Martin", ISO2 = "MF", ISO3 = "MAF", PhoneCode = "590", Continent = "North America", Capital = "Marigot", TimeZone = "America/Marigot", Currency = "Euro", Language = "fr", LangDescrip = "French (official), English, Dutch, French Patois, Spanish, Papiamento (dialect of Netherlands Antilles)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Saint Pierre and Miquelon", ISO2 = "PM", ISO3 = "SPM", PhoneCode = "508", Continent = "North America", Capital = "Saint-Pierre", TimeZone = "America/Miquelon", Currency = "Euro", Language = "fr-PM", LangDescrip = "French (official)", Mobile = "", LandLine = "4800" });
            //countries.Add(new Country { Name = "Saint Vincent and the Grenadines", ISO2 = "VC", ISO3 = "VCT", PhoneCode = "1-784", Continent = "North America", Capital = "Kingstown", TimeZone = "America/St_Vincent", Currency = "Dollar", Language = "en-VC,fr", LangDescrip = "English, French patois", Mobile = "135500", LandLine = "19400" });
            //countries.Add(new Country { Name = "Samoa", ISO2 = "WS", ISO3 = "WSM", PhoneCode = "685", Continent = "Oceania", Capital = "Apia", TimeZone = "Pacific/Apia", Currency = "Tala", Language = "sm,en-WS", LangDescrip = "Samoan (Polynesian) (official), English", Mobile = "167400", LandLine = "35300" });
            //countries.Add(new Country { Name = "San Marino", ISO2 = "SM", ISO3 = "SMR", PhoneCode = "378", Continent = "Europe", Capital = "San Marino", TimeZone = "Europe/San_Marino", Currency = "Euro", Language = "it-SM", LangDescrip = "Italian", Mobile = "36000", LandLine = "18700" });
            //countries.Add(new Country { Name = "Sao Tome and Principe", ISO2 = "ST", ISO3 = "STP", PhoneCode = "239", Continent = "Africa", Capital = "Sao Tome", TimeZone = "Africa/Sao_Tome", Currency = "Dobra", Language = "pt-ST", LangDescrip = "Portuguese 98.4% (official), Forro 36.2%, Cabo Verdian 8.5%, French 6.8%, Angolar 6.6%, English 4.9%, Lunguie 1%, other (including sign language) 2.4%", Mobile = "122000", LandLine = "8000" });
            //countries.Add(new Country { Name = "Saudi Arabia", ISO2 = "SA", ISO3 = "SAU", PhoneCode = "966", Continent = "Asia", Capital = "Riyadh", TimeZone = "Asia/Riyadh", Currency = "Rial", Language = "ar-SA", LangDescrip = "Arabic (official)", Mobile = "53000000", LandLine = "4800000" });
            //countries.Add(new Country { Name = "Senegal", ISO2 = "SN", ISO3 = "SEN", PhoneCode = "221", Continent = "Africa", Capital = "Dakar", TimeZone = "Africa/Dakar", Currency = "Franc", Language = "fr-SN,wo,fuc,mnk", LangDescrip = "French (official), Wolof, Pulaar, Jola, Mandinka", Mobile = "11470000", LandLine = "338200" });
            //countries.Add(new Country { Name = "Serbia", ISO2 = "RS", ISO3 = "SRB", PhoneCode = "381", Continent = "Europe", Capital = "Belgrade", TimeZone = "Europe/Belgrade", Currency = "Dinar", Language = "sr,hu,bs,rom", LangDescrip = "Serbian (official) 88.1%, Hungarian 3.4%, Bosnian 1.9%, Romany 1.4%, other 3.4%, undeclared or unknown 1.8%", Mobile = "9138000", LandLine = "2977000" });
            //countries.Add(new Country { Name = "Seychelles", ISO2 = "SC", ISO3 = "SYC", PhoneCode = "248", Continent = "Africa", Capital = "Victoria", TimeZone = "Indian/Mahe", Currency = "Rupee", Language = "en-SC,fr-SC", LangDescrip = "Seychellois Creole (official) 89.1%, English (official) 5.1%, French (official) 0.7%, other 3.8%, unspecified 1.4% (2010 est.)", Mobile = "138300", LandLine = "28900" });
            //countries.Add(new Country { Name = "Sierra Leone", ISO2 = "SL", ISO3 = "SLE", PhoneCode = "232", Continent = "Africa", Capital = "Freetown", TimeZone = "Africa/Freetown", Currency = "Leone", Language = "en-SL,men,tem", LangDescrip = "English (official, regular use limited to literate minority), Mende (principal vernacular in the south), Temne (principal vernacular in the north), Krio (English-based Creole, spoken by the descendants of freed Jamaican slaves who were settled in the Freetown area, a lingua franca and a first language for 10% of the population but understood by 95%)", Mobile = "2210000", LandLine = "18000" });
            //countries.Add(new Country { Name = "Singapore", ISO2 = "SG", ISO3 = "SGP", PhoneCode = "65", Continent = "Asia", Capital = "Singapore", TimeZone = "Asia/Singapore", Currency = "Dollar", Language = "cmn,en-SG,ms-SG,ta-SG,zh-SG", LangDescrip = "Mandarin (official) 36.3%, English (official) 29.8%, Malay (official) 11.9%, Hokkien 8.1%, Tamil (official) 4.4%, Cantonese 4.1%, Teochew 3.2%, other Indian languages 1.2%, other Chinese dialects 1.1%, other 1.1% (2010 est.)", Mobile = "8063000", LandLine = "1990000" });
            //countries.Add(new Country { Name = "Sint Maarten", ISO2 = "SX", ISO3 = "SXM", PhoneCode = "1-721", Continent = "North America", Capital = "Philipsburg", TimeZone = "America/Lower_Princes", Currency = "Guilder", Language = "nl,en", LangDescrip = "English (official) 67.5%, Spanish 12.9%, Creole 8.2%, Dutch (official) 4.2%, Papiamento (a Spanish-Portuguese-Dutch-English dialect) 2.2%, French 1.5%, other 3.5% (2001 census)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Slovakia", ISO2 = "SK", ISO3 = "SVK", PhoneCode = "421", Continent = "Europe", Capital = "Bratislava", TimeZone = "Europe/Bratislava", Currency = "Euro", Language = "sk,hu", LangDescrip = "Slovak (official) 78.6%, Hungarian 9.4%, Roma 2.3%, Ruthenian 1%, other or unspecified 8.8% (2011 est.)", Mobile = "6095000", LandLine = "975000" });
            //countries.Add(new Country { Name = "Slovenia", ISO2 = "SI", ISO3 = "SVN", PhoneCode = "386", Continent = "Europe", Capital = "Ljubljana", TimeZone = "Europe/Ljubljana", Currency = "Euro", Language = "sl,sh", LangDescrip = "Slovenian (official) 91.1%, Serbo-Croatian 4.5%, other or unspecified 4.4%, Italian (official, only in municipalities where Italian national communities reside), Hungarian (official, only in municipalities where Hungarian national communities reside) (2002 census)", Mobile = "2246000", LandLine = "825000" });
            //countries.Add(new Country { Name = "Solomon Islands", ISO2 = "SB", ISO3 = "SLB", PhoneCode = "677", Continent = "Oceania", Capital = "Honiara", TimeZone = "Pacific/Guadalcanal", Currency = "Dollar", Language = "en-SB,tpi", LangDescrip = "Melanesian pidgin (in much of the country is lingua franca), English (official but spoken by only 1%-2% of the population), 120 indigenous languages", Mobile = "302100", LandLine = "8060" });
            //countries.Add(new Country { Name = "Somalia", ISO2 = "SO", ISO3 = "SOM", PhoneCode = "252", Continent = "Africa", Capital = "Mogadishu", TimeZone = "Africa/Mogadishu", Currency = "Shilling", Language = "so-SO,ar-SO,it,en-SO", LangDescrip = "Somali (official), Arabic (official, according to the Transitional Federal Charter), Italian, English", Mobile = "658000", LandLine = "100000" });
            //countries.Add(new Country { Name = "South Africa", ISO2 = "ZA", ISO3 = "ZAF", PhoneCode = "27", Continent = "Africa", Capital = "Pretoria", TimeZone = "Africa/Johannesburg", Currency = "Rand", Language = "zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr", LangDescrip = "IsiZulu (official) 22.7%, IsiXhosa (official) 16%, Afrikaans (official) 13.5%, English (official) 9.6%, Sepedi (official) 9.1%, Setswana (official) 8%, Sesotho (official) 7.6%, Xitsonga (official) 4.5%, siSwati (official) 2.5%, Tshivenda (official) 2.4%, isiNdebele (official) 2.1%, sign language 0.5%, other 1.6% (2011 est.)", Mobile = "68400000", LandLine = "4030000" });
            //countries.Add(new Country { Name = "South Korea", ISO2 = "KR", ISO3 = "KOR", PhoneCode = "82", Continent = "Asia", Capital = "Seoul", TimeZone = "Asia/Seoul", Currency = "Won", Language = "ko-KR,en", LangDescrip = "Korean, English (widely taught in junior high and high school)", Mobile = "53625000", LandLine = "30100000" });
            //countries.Add(new Country { Name = "South Sudan", ISO2 = "SS", ISO3 = "SSD", PhoneCode = "211", Continent = "Africa", Capital = "Juba", TimeZone = "Africa/Juba", Currency = "Pound", Language = "en", LangDescrip = "English (official), Arabic (includes Juba and Sudanese variants), regional languages include Dinka, Nuer, Bari, Zande, Shilluk", Mobile = "2000000", LandLine = "2200" });
            //countries.Add(new Country { Name = "Spain", ISO2 = "ES", ISO3 = "ESP", PhoneCode = "34", Continent = "Europe", Capital = "Madrid", TimeZone = "Europe/Madrid", Currency = "Euro", Language = "es-ES,ca,gl,eu,oc", LangDescrip = "Castilian Spanish (official) 74%, Catalan 17%, Galician 7%, and Basque 2%", Mobile = "50663000", LandLine = "19220000" });
            //countries.Add(new Country { Name = "Sri Lanka", ISO2 = "LK", ISO3 = "LKA", PhoneCode = "94", Continent = "Asia", Capital = "Colombo", TimeZone = "Asia/Colombo", Currency = "Rupee", Language = "si,ta,en", LangDescrip = "Sinhala (official and national language) 74%, Tamil (national language) 18%, other 8%", Mobile = "19533000", LandLine = "2796000" });
            //countries.Add(new Country { Name = "Sudan", ISO2 = "SD", ISO3 = "SDN", PhoneCode = "249", Continent = "Africa", Capital = "Khartoum", TimeZone = "Africa/Khartoum", Currency = "Pound", Language = "ar-SD,en,fia", LangDescrip = "Arabic (official), English (official), Nubian, Ta Bedawie, Fur", Mobile = "27659000", LandLine = "425000" });
            //countries.Add(new Country { Name = "Suriname", ISO2 = "SR", ISO3 = "SUR", PhoneCode = "597", Continent = "South America", Capital = "Paramaribo", TimeZone = "America/Paramaribo", Currency = "Dollar", Language = "nl-SR,en,srn,hns,jv", LangDescrip = "Dutch (official), English (widely spoken), Sranang Tongo (Surinamese, sometimes called Taki-Taki, is native language of Creoles and much of the younger population and is lingua franca among others), Caribbean Hindustani (a dialect of Hindi), Javanese", Mobile = "977000", LandLine = "83000" });
            //countries.Add(new Country { Name = "Svalbard and Jan Mayen", ISO2 = "SJ", ISO3 = "SJM", PhoneCode = "47", Continent = "Europe", Capital = "Longyearbyen", TimeZone = "Arctic/Longyearbyen", Currency = "Krone", Language = "no,ru", LangDescrip = "Norwegian, Russian", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Swaziland", ISO2 = "SZ", ISO3 = "SWZ", PhoneCode = "268", Continent = "Africa", Capital = "Mbabane", TimeZone = "Africa/Mbabane", Currency = "Lilangeni", Language = "en-SZ,ss-SZ", LangDescrip = "English (official, used for government business), siSwati (official)", Mobile = "805000", LandLine = "48600" });
            //countries.Add(new Country { Name = "Sweden", ISO2 = "SE", ISO3 = "SWE", PhoneCode = "46", Continent = "Europe", Capital = "Stockholm", TimeZone = "Europe/Stockholm", Currency = "Krona", Language = "sv-SE,se,sma,fi-SE", LangDescrip = "Swedish (official), small Sami- and Finnish-speaking minorities", Mobile = "11643000", LandLine = "4321000" });
            //countries.Add(new Country { Name = "Switzerland", ISO2 = "CH", ISO3 = "CHE", PhoneCode = "41", Continent = "Europe", Capital = "Berne", TimeZone = "Europe/Zurich", Currency = "Franc", Language = "de-CH,fr-CH,it-CH,rm", LangDescrip = "German (official) 64.9%, French (official) 22.6%, Italian (official) 8.3%, Serbo-Croatian 2.5%, Albanian 2.6%, Portuguese 3.4%, Spanish 2.2%, English 4.6%, Romansch (official) 0.5%, other 5.1%", Mobile = "10460000", LandLine = "4382000" });
            //countries.Add(new Country { Name = "Syria", ISO2 = "SY", ISO3 = "SYR", PhoneCode = "963", Continent = "Asia", Capital = "Damascus", TimeZone = "Asia/Damascus", Currency = "Pound", Language = "ar-SY,ku,hy,arc,fr,en", LangDescrip = "Arabic (official), Kurdish, Armenian, Aramaic, Circassian (widely understood); French, English (somewhat understood)", Mobile = "12928000", LandLine = "4425000" });
            //countries.Add(new Country { Name = "Taiwan", ISO2 = "TW", ISO3 = "TWN", PhoneCode = "886", Continent = "Asia", Capital = "Taipei", TimeZone = "Asia/Taipei", Currency = "Dollar", Language = "zh-TW,zh,nan,hak", LangDescrip = "Mandarin Chinese (official), Taiwanese (Min), Hakka dialects", Mobile = "29455000", LandLine = "15998000" });
            //countries.Add(new Country { Name = "Tajikistan", ISO2 = "TJ", ISO3 = "TJK", PhoneCode = "992", Continent = "Asia", Capital = "Dushanbe", TimeZone = "Asia/Dushanbe", Currency = "Somoni", Language = "tg,ru", LangDescrip = "Tajik (official), Russian widely used in government and business", Mobile = "6528000", LandLine = "393000" });
            //countries.Add(new Country { Name = "Tanzania", ISO2 = "TZ", ISO3 = "TZA", PhoneCode = "255", Continent = "Africa", Capital = "Dodoma", TimeZone = "Africa/Dar_es_Salaam", Currency = "Shilling", Language = "sw-TZ,en,ar", LangDescrip = "Kiswahili or Swahili (official), Kiunguja (name for Swahili in Zanzibar), English (official, primary language of commerce, administration, and higher education), Arabic (widely spoken in Zanzibar), many local languages", Mobile = "27220000", LandLine = "161100" });
            //countries.Add(new Country { Name = "Thailand", ISO2 = "TH", ISO3 = "THA", PhoneCode = "66", Continent = "Asia", Capital = "Bangkok", TimeZone = "Asia/Bangkok", Currency = "Baht", Language = "th,en", LangDescrip = "Thai (official) 90.7%, Burmese 1.3%, other 8%", Mobile = "84075000", LandLine = "6391000" });
            //countries.Add(new Country { Name = "Togo", ISO2 = "TG", ISO3 = "TGO", PhoneCode = "228", Continent = "Africa", Capital = "Lome", TimeZone = "Africa/Lome", Currency = "Franc", Language = "fr-TG,ee,hna,kbp,dag,ha", LangDescrip = "French (official, the language of commerce), Ewe and Mina (the two major African languages in the south), Kabye (sometimes spelled Kabiye) and Dagomba (the two major African languages in the north)", Mobile = "3518000", LandLine = "225000" });
            //countries.Add(new Country { Name = "Tokelau", ISO2 = "TK", ISO3 = "TKL", PhoneCode = "690", Continent = "Oceania", Capital = "", TimeZone = "Pacific/Fakaofo", Currency = "Dollar", Language = "tkl,en-TK", LangDescrip = "Tokelauan 93.5% (a Polynesian language), English 58.9%, Samoan 45.5%, Tuvaluan 11.6%, Kiribati 2.7%, other 2.5%, none 4.1%, unspecified 0.6%", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Tonga", ISO2 = "TO", ISO3 = "TON", PhoneCode = "676", Continent = "Oceania", Capital = "Nuku'alofa", TimeZone = "Pacific/Tongatapu", Currency = "Pa'anga", Language = "to,en-TO", LangDescrip = "English and Tongan 87%, Tongan (official) 10.7%, English (official) 1.2%, other 1.1%, uspecified 0.03% (2006 est.)", Mobile = "56000", LandLine = "30000" });
            //countries.Add(new Country { Name = "Trinidad and Tobago", ISO2 = "TT", ISO3 = "TTO", PhoneCode = "1-868", Continent = "North America", Capital = "Port of Spain", TimeZone = "America/Port_of_Spain", Currency = "Dollar", Language = "en-TT,hns,fr,es,zh", LangDescrip = "English (official), Caribbean Hindustani (a dialect of Hindi), French, Spanish, Chinese", Mobile = "1884000", LandLine = "287000" });
            //countries.Add(new Country { Name = "Tunisia", ISO2 = "TN", ISO3 = "TUN", PhoneCode = "216", Continent = "Africa", Capital = "Tunis", TimeZone = "Africa/Tunis", Currency = "Dinar", Language = "ar-TN,fr", LangDescrip = "Arabic (official, one of the languages of commerce), French (commerce), Berber (Tamazight)", Mobile = "12840000", LandLine = "1105000" });
            //countries.Add(new Country { Name = "Turkey", ISO2 = "TR", ISO3 = "TUR", PhoneCode = "90", Continent = "Asia", Capital = "Ankara", TimeZone = "Europe/Istanbul", Currency = "Lira", Language = "tr-TR,ku,diq,az,av", LangDescrip = "Turkish (official), Kurdish, other minority languages", Mobile = "67680000", LandLine = "13860000" });
            //countries.Add(new Country { Name = "Turkmenistan", ISO2 = "TM", ISO3 = "TKM", PhoneCode = "993", Continent = "Asia", Capital = "Ashgabat", TimeZone = "Asia/Ashgabat", Currency = "Manat", Language = "tk,ru,uz", LangDescrip = "Turkmen (official) 72%, Russian 12%, Uzbek 9%, other 7%", Mobile = "3953000", LandLine = "575000" });
            //countries.Add(new Country { Name = "Turks and Caicos Islands", ISO2 = "TC", ISO3 = "TCA", PhoneCode = "1-649", Continent = "North America", Capital = "Cockburn Town", TimeZone = "America/Grand_Turk", Currency = "Dollar", Language = "en-TC", LangDescrip = "English (official)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Tuvalu", ISO2 = "TV", ISO3 = "TUV", PhoneCode = "688", Continent = "Oceania", Capital = "Funafuti", TimeZone = "Pacific/Funafuti", Currency = "Dollar", Language = "tvl,en,sm,gil", LangDescrip = "Tuvaluan (official), English (official), Samoan, Kiribati (on the island of Nui)", Mobile = "2800", LandLine = "1450" });
            //countries.Add(new Country { Name = "U.S. Virgin Islands", ISO2 = "VI", ISO3 = "VIR", PhoneCode = "1-340", Continent = "North America", Capital = "Charlotte Amalie", TimeZone = "America/St_Thomas", Currency = "Dollar", Language = "en-VI", LangDescrip = "English 74.7%, Spanish or Spanish Creole 16.8%, French or French Creole 6.6%, other 1.9% (2000 census)", Mobile = "80300", LandLine = "75800" });
            //countries.Add(new Country { Name = "Uganda", ISO2 = "UG", ISO3 = "UGA", PhoneCode = "256", Continent = "Africa", Capital = "Kampala", TimeZone = "Africa/Kampala", Currency = "Shilling", Language = "en-UG,lg,sw,ar", LangDescrip = "English (official national language, taught in grade schools, used in courts of law and by most newspapers and some radio broadcasts), Ganda or Luganda (most widely used of the Niger-Congo languages, preferred for native language publications in the capital and may be taught in school), other Niger-Congo languages, Nilo-Saharan languages, Swahili, Arabic", Mobile = "16355000", LandLine = "315000" });
            //countries.Add(new Country { Name = "Ukraine", ISO2 = "UA", ISO3 = "UKR", PhoneCode = "380", Continent = "Europe", Capital = "Kiev", TimeZone = "Europe/Kiev", Currency = "Hryvnia", Language = "uk,ru-UA,rom,pl,hu", LangDescrip = "Ukrainian (official) 67%, Russian (regional language) 24%, other (includes small Romanian-, Polish-, and Hungarian-speaking minorities) 9%", Mobile = "59344000", LandLine = "12182000" });
            //countries.Add(new Country { Name = "United Arab Emirates", ISO2 = "AE", ISO3 = "ARE", PhoneCode = "971", Continent = "Asia", Capital = "Abu Dhabi", TimeZone = "Asia/Dubai", Currency = "Dirham", Language = "ar-AE,fa,en,hi,ur", LangDescrip = "Arabic (official), Persian, English, Hindi, Urdu", Mobile = "13775000", LandLine = "1967000" });
            //countries.Add(new Country { Name = "United Kingdom", ISO2 = "GB", ISO3 = "GBR", PhoneCode = "44", Continent = "Europe", Capital = "London", TimeZone = "Europe/London", Currency = "Pound", Language = "en-GB,cy-GB,gd", LangDescrip = "English", Mobile = "82109000", LandLine = "33010000" });
            countries.Add(new Country { Name = "United States", ISO2 = "US", ISO3 = "USA", PhoneCode = "1", Continent = "North America", Capital = "Washington", TimeZone = "America/New_York", Currency = "Dollar", Language = "en-US,es-US,haw,fr", LangDescrip = "English 82.1%, Spanish 10.7%, other Indo-European 3.8%, Asian and Pacific island 2.7%, other 0.7% (2000 census)", Mobile = "310000000", LandLine = "139000000" });
            //countries.Add(new Country { Name = "Uruguay", ISO2 = "UY", ISO3 = "URY", PhoneCode = "598", Continent = "South America", Capital = "Montevideo", TimeZone = "America/Montevideo", Currency = "Peso", Language = "es-UY", LangDescrip = "Spanish (official), Portunol, Brazilero (Portuguese-Spanish mix on the Brazilian frontier)", Mobile = "5000000", LandLine = "1010000" });
            //countries.Add(new Country { Name = "Uzbekistan", ISO2 = "UZ", ISO3 = "UZB", PhoneCode = "998", Continent = "Asia", Capital = "Tashkent", TimeZone = "Asia/Tashkent", Currency = "Som", Language = "uz,ru,tg", LangDescrip = "Uzbek (official) 74.3%, Russian 14.2%, Tajik 4.4%, other 7.1%", Mobile = "20274000", LandLine = "1963000" });
            //countries.Add(new Country { Name = "Vanuatu", ISO2 = "VU", ISO3 = "VUT", PhoneCode = "678", Continent = "Oceania", Capital = "Port Vila", TimeZone = "Pacific/Efate", Currency = "Vatu", Language = "bi,en-VU,fr-VU", LangDescrip = "local languages (more than 100) 63.2%, Bislama (official; creole) 33.7%, English (official) 2%, French (official) 0.6%, other 0.5% (2009 est.)", Mobile = "137000", LandLine = "5800" });
            //countries.Add(new Country { Name = "Vatican", ISO2 = "VA", ISO3 = "VAT", PhoneCode = "379", Continent = "Europe", Capital = "Vatican City", TimeZone = "Europe/Vatican", Currency = "Euro", Language = "la,it,fr", LangDescrip = "Latin, Italian, French", Mobile = "", LandLine = "" });
            countries.Add(new Country { Name = "Venezuela", ISO2 = "VE", ISO3 = "VEN", PhoneCode = "58", Continent = "South America", Capital = "Caracas", TimeZone = "America/Caracas", Currency = "Bolivar", Language = "es-VE", LangDescrip = "Spanish (official), numerous indigenous dialects", Mobile = "30520000", LandLine = "7650000" });
            //countries.Add(new Country { Name = "Vietnam", ISO2 = "VN", ISO3 = "VNM", PhoneCode = "84", Continent = "Asia", Capital = "Hanoi", TimeZone = "Asia/Ho_Chi_Minh", Currency = "Dong", Language = "vi,en,fr,zh,km", LangDescrip = "Vietnamese (official), English (increasingly favored as a second language), some French, Chinese, and Khmer, mountain area languages (Mon-Khmer and Malayo-Polynesian)", Mobile = "134066000", LandLine = "10191000" });
            //countries.Add(new Country { Name = "Wallis and Futuna", ISO2 = "WF", ISO3 = "WLF", PhoneCode = "681", Continent = "Oceania", Capital = "Mata Utu", TimeZone = "Pacific/Wallis", Currency = "Franc", Language = "wls,fud,fr-WF", LangDescrip = "Wallisian (indigenous Polynesian language) 58.9%, Futunian 30.1%, French (official) 10.8%, other 0.2% (2003 census)", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Western Sahara", ISO2 = "EH", ISO3 = "ESH", PhoneCode = "212", Continent = "Africa", Capital = "El-Aaiun", TimeZone = "Africa/El_Aaiun", Currency = "Dirham", Language = "ar,mey", LangDescrip = "Standard Arabic (national), Hassaniya Arabic, Moroccan Arabic", Mobile = "", LandLine = "" });
            //countries.Add(new Country { Name = "Yemen", ISO2 = "YE", ISO3 = "YEM", PhoneCode = "967", Continent = "Asia", Capital = "Sanaa", TimeZone = "Asia/Aden", Currency = "Rial", Language = "ar-YE", LangDescrip = "Arabic (official)", Mobile = "13900000", LandLine = "1100000" });
            //countries.Add(new Country { Name = "Zambia", ISO2 = "ZM", ISO3 = "ZMB", PhoneCode = "260", Continent = "Africa", Capital = "Lusaka", TimeZone = "Africa/Lusaka", Currency = "Kwacha", Language = "en-ZM,bem,loz,lun,lue,ny,toi", LangDescrip = "Bembe 33.4%, Nyanja 14.7%, Tonga 11.4%, Lozi 5.5%, Chewa 4.5%, Nsenga 2.9%, Tumbuka 2.5%, Lunda (North Western) 1.9%, Kaonde 1.8%, Lala 1.8%, Lamba 1.8%, English (official) 1.7%, Luvale 1.5%, Mambwe 1.3%, Namwanga 1.2%, Lenje 1.1%, Bisa 1%, other 9.2%, unspecified 0.4%", Mobile = "10525000", LandLine = "82500" });
            //countries.Add(new Country { Name = "Zimbabwe", ISO2 = "ZW", ISO3 = "ZWE", PhoneCode = "263", Continent = "Africa", Capital = "Harare", TimeZone = "Africa/Harare", Currency = "Dollar", Language = "en-ZW,sn,nr,nd", LangDescrip = "English (official), Shona, Sindebele (the language of the Ndebele, sometimes called Ndebele), numerous but minor tribal dialects", Mobile = "12614000", LandLine = "301600" });
           

            return countries;

        }

        public static IList<cCountry> InfoListByDemand(string continent)
        {
            IList<Country> countries = new List<Country>();
            IList<cCountry> ccountries = new List<cCountry>();
            countries = Info();

            if(continent != "@") 
            {
                var countries2 = (from list in countries where list.Continent.Contains(continent) select list);

                foreach(Country item in countries2)
                {
                    ccountries.Add(new cCountry { Name = item.Name, ISO2 = item.ISO2,  PhoneCode = item.PhoneCode });
                }

            }
            return ccountries;
        }


        public static string GetCountryPhoneCode(string Code) 
        {
            IList<Country> countries = new List<Country>();

            countries = Info();

            var countriesPhoneCode = (from list in countries where list.ISO2.Contains(Code) select list.PhoneCode).First();

            return countriesPhoneCode.ToString();


        }
        public static string GetCountryName(string Code)
        {
            IList<Country> countries = new List<Country>();

            countries = Info();

            var countriesPhoneCode = (from list in countries where list.ISO2.Contains(Code) select list.Name).First();

            return countriesPhoneCode.ToString();


        }
    }
}
