//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.ws.cvxpress {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("com.ws.cvxpress.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        internal static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        internal static string OfferBox {
            get {
                return ResourceManager.GetString("OfferBox", resourceCulture);
            }
        }
        
        internal static string CapacityTaken {
            get {
                return ResourceManager.GetString("CapacityTaken", resourceCulture);
            }
        }
        
        internal static string NoCardsLoaded {
            get {
                return ResourceManager.GetString("NoCardsLoaded", resourceCulture);
            }
        }
        
        internal static string DeleteCard {
            get {
                return ResourceManager.GetString("DeleteCard", resourceCulture);
            }
        }
        
        internal static string existsCard {
            get {
                return ResourceManager.GetString("existsCard", resourceCulture);
            }
        }
        
        internal static string newCard {
            get {
                return ResourceManager.GetString("newCard", resourceCulture);
            }
        }
        
        internal static string MyCards {
            get {
                return ResourceManager.GetString("MyCards", resourceCulture);
            }
        }
        
        internal static string DeliveryPrice {
            get {
                return ResourceManager.GetString("DeliveryPrice", resourceCulture);
            }
        }
        
        internal static string DeletingCard {
            get {
                return ResourceManager.GetString("DeletingCard", resourceCulture);
            }
        }
        
        internal static string NoDelete {
            get {
                return ResourceManager.GetString("NoDelete", resourceCulture);
            }
        }
        
        internal static string SelectCard {
            get {
                return ResourceManager.GetString("SelectCard", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string ContinueRequest {
            get {
                return ResourceManager.GetString("ContinueRequest", resourceCulture);
            }
        }
        
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        internal static string OfferBoxCreated {
            get {
                return ResourceManager.GetString("OfferBoxCreated", resourceCulture);
            }
        }
        
        internal static string RequestBox {
            get {
                return ResourceManager.GetString("RequestBox", resourceCulture);
            }
        }
        
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string GenInfo {
            get {
                return ResourceManager.GetString("GenInfo", resourceCulture);
            }
        }
        
        internal static string AdminInfo {
            get {
                return ResourceManager.GetString("AdminInfo", resourceCulture);
            }
        }
        
        internal static string TravelerAuth {
            get {
                return ResourceManager.GetString("TravelerAuth", resourceCulture);
            }
        }
        
        internal static string NewTravelers {
            get {
                return ResourceManager.GetString("NewTravelers", resourceCulture);
            }
        }
        
        internal static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        internal static string AdminOptions {
            get {
                return ResourceManager.GetString("AdminOptions", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        internal static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        internal static string CurrentPass {
            get {
                return ResourceManager.GetString("CurrentPass", resourceCulture);
            }
        }
        
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        internal static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        internal static string ConfirmReq {
            get {
                return ResourceManager.GetString("ConfirmReq", resourceCulture);
            }
        }
        
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        internal static string NoticeLogin {
            get {
                return ResourceManager.GetString("NoticeLogin", resourceCulture);
            }
        }
        
        internal static string NoticeEmptyData {
            get {
                return ResourceManager.GetString("NoticeEmptyData", resourceCulture);
            }
        }
        
        internal static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        internal static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        internal static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        internal static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        internal static string NoticeRegister {
            get {
                return ResourceManager.GetString("NoticeRegister", resourceCulture);
            }
        }
        
        internal static string NoticeEmptyRegister {
            get {
                return ResourceManager.GetString("NoticeEmptyRegister", resourceCulture);
            }
        }
        
        internal static string NoticeForgot {
            get {
                return ResourceManager.GetString("NoticeForgot", resourceCulture);
            }
        }
        
        internal static string NoticeEmptyForgot {
            get {
                return ResourceManager.GetString("NoticeEmptyForgot", resourceCulture);
            }
        }
        
        internal static string AcceptedTerms {
            get {
                return ResourceManager.GetString("AcceptedTerms", resourceCulture);
            }
        }
        
        internal static string NoPasswordMatch {
            get {
                return ResourceManager.GetString("NoPasswordMatch", resourceCulture);
            }
        }
        
        internal static string ConfPassword {
            get {
                return ResourceManager.GetString("ConfPassword", resourceCulture);
            }
        }
        
        internal static string NoFBPublish {
            get {
                return ResourceManager.GetString("NoFBPublish", resourceCulture);
            }
        }
        
        internal static string MyOffers {
            get {
                return ResourceManager.GetString("MyOffers", resourceCulture);
            }
        }
        
        internal static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        internal static string RequestItem {
            get {
                return ResourceManager.GetString("RequestItem", resourceCulture);
            }
        }
        
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        internal static string RequestsAcepted {
            get {
                return ResourceManager.GetString("RequestsAcepted", resourceCulture);
            }
        }
        
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string LoadingNew {
            get {
                return ResourceManager.GetString("LoadingNew", resourceCulture);
            }
        }
        
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        internal static string AuthSent {
            get {
                return ResourceManager.GetString("AuthSent", resourceCulture);
            }
        }
        
        internal static string DeliverItem {
            get {
                return ResourceManager.GetString("DeliverItem", resourceCulture);
            }
        }
        
        internal static string autorizecharge {
            get {
                return ResourceManager.GetString("autorizecharge", resourceCulture);
            }
        }
        
        internal static string autorizechargechanged {
            get {
                return ResourceManager.GetString("autorizechargechanged", resourceCulture);
            }
        }
        
        internal static string WaitforAuth {
            get {
                return ResourceManager.GetString("WaitforAuth", resourceCulture);
            }
        }
        
        internal static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        internal static string AuthDenied {
            get {
                return ResourceManager.GetString("AuthDenied", resourceCulture);
            }
        }
        
        internal static string AuthQuestion {
            get {
                return ResourceManager.GetString("AuthQuestion", resourceCulture);
            }
        }
        
        internal static string WeightAvail {
            get {
                return ResourceManager.GetString("WeightAvail", resourceCulture);
            }
        }
        
        internal static string WeightAvail2 {
            get {
                return ResourceManager.GetString("WeightAvail2", resourceCulture);
            }
        }
        
        internal static string WeightAvailtravel {
            get {
                return ResourceManager.GetString("WeightAvailtravel", resourceCulture);
            }
        }
        
        internal static string WeightHint {
            get {
                return ResourceManager.GetString("WeightHint", resourceCulture);
            }
        }
        
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        internal static string VolumeHint {
            get {
                return ResourceManager.GetString("VolumeHint", resourceCulture);
            }
        }
        
        internal static string DeliveredAt {
            get {
                return ResourceManager.GetString("DeliveredAt", resourceCulture);
            }
        }
        
        internal static string DeliveredAtHint {
            get {
                return ResourceManager.GetString("DeliveredAtHint", resourceCulture);
            }
        }
        
        internal static string Traveler {
            get {
                return ResourceManager.GetString("Traveler", resourceCulture);
            }
        }
        
        internal static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        internal static string NotNew {
            get {
                return ResourceManager.GetString("NotNew", resourceCulture);
            }
        }
        
        internal static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        internal static string AtLeastCategory {
            get {
                return ResourceManager.GetString("AtLeastCategory", resourceCulture);
            }
        }
        
        internal static string AtLeastType {
            get {
                return ResourceManager.GetString("AtLeastType", resourceCulture);
            }
        }
        
        internal static string AtLeastDelivery {
            get {
                return ResourceManager.GetString("AtLeastDelivery", resourceCulture);
            }
        }
        
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        internal static string Slogan {
            get {
                return ResourceManager.GetString("Slogan", resourceCulture);
            }
        }
        
        internal static string OrLoginWith {
            get {
                return ResourceManager.GetString("OrLoginWith", resourceCulture);
            }
        }
        
        internal static string OrRegisterWith {
            get {
                return ResourceManager.GetString("OrRegisterWith", resourceCulture);
            }
        }
        
        internal static string RegisterText {
            get {
                return ResourceManager.GetString("RegisterText", resourceCulture);
            }
        }
        
        internal static string AgeLimitText {
            get {
                return ResourceManager.GetString("AgeLimitText", resourceCulture);
            }
        }
        
        internal static string ForgotPassText {
            get {
                return ResourceManager.GetString("ForgotPassText", resourceCulture);
            }
        }
        
        internal static string SelectProfile {
            get {
                return ResourceManager.GetString("SelectProfile", resourceCulture);
            }
        }
        
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        internal static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        internal static string VZ {
            get {
                return ResourceManager.GetString("VZ", resourceCulture);
            }
        }
        
        internal static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        internal static string SelectPicture {
            get {
                return ResourceManager.GetString("SelectPicture", resourceCulture);
            }
        }
        
        internal static string AddPictures {
            get {
                return ResourceManager.GetString("AddPictures", resourceCulture);
            }
        }
        
        internal static string IdPhoto {
            get {
                return ResourceManager.GetString("IdPhoto", resourceCulture);
            }
        }
        
        internal static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        internal static string LoadingResources {
            get {
                return ResourceManager.GetString("LoadingResources", resourceCulture);
            }
        }
        
        internal static string LookingForUpdates {
            get {
                return ResourceManager.GetString("LookingForUpdates", resourceCulture);
            }
        }
        
        internal static string DeliveryOptions {
            get {
                return ResourceManager.GetString("DeliveryOptions", resourceCulture);
            }
        }
        
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        internal static string ProfileSuccess {
            get {
                return ResourceManager.GetString("ProfileSuccess", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string ProfileExists {
            get {
                return ResourceManager.GetString("ProfileExists", resourceCulture);
            }
        }
        
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        internal static string ProfileWrong {
            get {
                return ResourceManager.GetString("ProfileWrong", resourceCulture);
            }
        }
        
        internal static string SentCode {
            get {
                return ResourceManager.GetString("SentCode", resourceCulture);
            }
        }
        
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        internal static string VerifySuccess {
            get {
                return ResourceManager.GetString("VerifySuccess", resourceCulture);
            }
        }
        
        internal static string ListNumberMessage {
            get {
                return ResourceManager.GetString("ListNumberMessage", resourceCulture);
            }
        }
        
        internal static string ListCaMessage {
            get {
                return ResourceManager.GetString("ListCaMessage", resourceCulture);
            }
        }
        
        internal static string TravelAvailability {
            get {
                return ResourceManager.GetString("TravelAvailability", resourceCulture);
            }
        }
        
        internal static string Specs {
            get {
                return ResourceManager.GetString("Specs", resourceCulture);
            }
        }
        
        internal static string Wide {
            get {
                return ResourceManager.GetString("Wide", resourceCulture);
            }
        }
        
        internal static string WideHint {
            get {
                return ResourceManager.GetString("WideHint", resourceCulture);
            }
        }
        
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        internal static string HeightHint {
            get {
                return ResourceManager.GetString("HeightHint", resourceCulture);
            }
        }
        
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        internal static string LongHint {
            get {
                return ResourceManager.GetString("LongHint", resourceCulture);
            }
        }
        
        internal static string TravelerPresentation {
            get {
                return ResourceManager.GetString("TravelerPresentation", resourceCulture);
            }
        }
        
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        internal static string TravelerInstructions {
            get {
                return ResourceManager.GetString("TravelerInstructions", resourceCulture);
            }
        }
        
        internal static string RequestPresentation {
            get {
                return ResourceManager.GetString("RequestPresentation", resourceCulture);
            }
        }
        
        internal static string RequestInstructions {
            get {
                return ResourceManager.GetString("RequestInstructions", resourceCulture);
            }
        }
        
        internal static string LoadingProfile {
            get {
                return ResourceManager.GetString("LoadingProfile", resourceCulture);
            }
        }
        
        internal static string ChangeToTraveler {
            get {
                return ResourceManager.GetString("ChangeToTraveler", resourceCulture);
            }
        }
        
        internal static string ChangeToSender {
            get {
                return ResourceManager.GetString("ChangeToSender", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Nopicture {
            get {
                return ResourceManager.GetString("Nopicture", resourceCulture);
            }
        }
        
        internal static string NoTextIdents {
            get {
                return ResourceManager.GetString("NoTextIdents", resourceCulture);
            }
        }
        
        internal static string ModifyPresentation {
            get {
                return ResourceManager.GetString("ModifyPresentation", resourceCulture);
            }
        }
        
        internal static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        internal static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        internal static string MyIds {
            get {
                return ResourceManager.GetString("MyIds", resourceCulture);
            }
        }
        
        internal static string UpdateDone {
            get {
                return ResourceManager.GetString("UpdateDone", resourceCulture);
            }
        }
        
        internal static string UpdateUnDone {
            get {
                return ResourceManager.GetString("UpdateUnDone", resourceCulture);
            }
        }
        
        internal static string TextIdents {
            get {
                return ResourceManager.GetString("TextIdents", resourceCulture);
            }
        }
        
        internal static string TravelInfo {
            get {
                return ResourceManager.GetString("TravelInfo", resourceCulture);
            }
        }
        
        internal static string GeneralUpdate {
            get {
                return ResourceManager.GetString("GeneralUpdate", resourceCulture);
            }
        }
        
        internal static string TravelRequests {
            get {
                return ResourceManager.GetString("TravelRequests", resourceCulture);
            }
        }
        
        internal static string RequestOnRoute {
            get {
                return ResourceManager.GetString("RequestOnRoute", resourceCulture);
            }
        }
        
        internal static string UnitUpdate {
            get {
                return ResourceManager.GetString("UnitUpdate", resourceCulture);
            }
        }
        
        internal static string TravelUnitRequest {
            get {
                return ResourceManager.GetString("TravelUnitRequest", resourceCulture);
            }
        }
        
        internal static string BuyItemText {
            get {
                return ResourceManager.GetString("BuyItemText", resourceCulture);
            }
        }
        
        internal static string TravelStarted {
            get {
                return ResourceManager.GetString("TravelStarted", resourceCulture);
            }
        }
        
        internal static string TravelFinished {
            get {
                return ResourceManager.GetString("TravelFinished", resourceCulture);
            }
        }
        
        internal static string ItemDelivered {
            get {
                return ResourceManager.GetString("ItemDelivered", resourceCulture);
            }
        }
        
        internal static string UpdateState {
            get {
                return ResourceManager.GetString("UpdateState", resourceCulture);
            }
        }
        
        internal static string UpdateInstructionsUnit {
            get {
                return ResourceManager.GetString("UpdateInstructionsUnit", resourceCulture);
            }
        }
        
        internal static string AcceptRequest {
            get {
                return ResourceManager.GetString("AcceptRequest", resourceCulture);
            }
        }
        
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        internal static string ItemDesc {
            get {
                return ResourceManager.GetString("ItemDesc", resourceCulture);
            }
        }
        
        internal static string ItemFind {
            get {
                return ResourceManager.GetString("ItemFind", resourceCulture);
            }
        }
        
        internal static string ItemQty {
            get {
                return ResourceManager.GetString("ItemQty", resourceCulture);
            }
        }
        
        internal static string ItemCat {
            get {
                return ResourceManager.GetString("ItemCat", resourceCulture);
            }
        }
        
        internal static string PrefArrival {
            get {
                return ResourceManager.GetString("PrefArrival", resourceCulture);
            }
        }
        
        internal static string PrefArrival1 {
            get {
                return ResourceManager.GetString("PrefArrival1", resourceCulture);
            }
        }
        
        internal static string DocDate {
            get {
                return ResourceManager.GetString("DocDate", resourceCulture);
            }
        }
        
        internal static string NoCompleteObjetc {
            get {
                return ResourceManager.GetString("NoCompleteObjetc", resourceCulture);
            }
        }
        
        internal static string InvalidDates {
            get {
                return ResourceManager.GetString("InvalidDates", resourceCulture);
            }
        }
        
        internal static string ProductValue {
            get {
                return ResourceManager.GetString("ProductValue", resourceCulture);
            }
        }
        
        internal static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
        
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        internal static string UserPhoto {
            get {
                return ResourceManager.GetString("UserPhoto", resourceCulture);
            }
        }
        
        internal static string Articlestitle {
            get {
                return ResourceManager.GetString("Articlestitle", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string ProductPhoto {
            get {
                return ResourceManager.GetString("ProductPhoto", resourceCulture);
            }
        }
        
        internal static string OnlyOnePick {
            get {
                return ResourceManager.GetString("OnlyOnePick", resourceCulture);
            }
        }
        
        internal static string Only3 {
            get {
                return ResourceManager.GetString("Only3", resourceCulture);
            }
        }
        
        internal static string InfoForYou {
            get {
                return ResourceManager.GetString("InfoForYou", resourceCulture);
            }
        }
        
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        internal static string WelcomeSubTitleTraveler {
            get {
                return ResourceManager.GetString("WelcomeSubTitleTraveler", resourceCulture);
            }
        }
        
        internal static string WelcomeSubTitleSender {
            get {
                return ResourceManager.GetString("WelcomeSubTitleSender", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string ActualPassNo {
            get {
                return ResourceManager.GetString("ActualPassNo", resourceCulture);
            }
        }
        
        internal static string selectDestiny {
            get {
                return ResourceManager.GetString("selectDestiny", resourceCulture);
            }
        }
        
        internal static string DestinyInfo {
            get {
                return ResourceManager.GetString("DestinyInfo", resourceCulture);
            }
        }
        
        internal static string SeeFile {
            get {
                return ResourceManager.GetString("SeeFile", resourceCulture);
            }
        }
        
        internal static string CheckReaded {
            get {
                return ResourceManager.GetString("CheckReaded", resourceCulture);
            }
        }
        
        internal static string revdoc {
            get {
                return ResourceManager.GetString("revdoc", resourceCulture);
            }
        }
        
        internal static string RecoveryEmailSend {
            get {
                return ResourceManager.GetString("RecoveryEmailSend", resourceCulture);
            }
        }
        
        internal static string Resp {
            get {
                return ResourceManager.GetString("Resp", resourceCulture);
            }
        }
        
        internal static string CServicePresentation {
            get {
                return ResourceManager.GetString("CServicePresentation", resourceCulture);
            }
        }
        
        internal static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        internal static string ResponseUser {
            get {
                return ResourceManager.GetString("ResponseUser", resourceCulture);
            }
        }
        
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        internal static string AdjustingImage {
            get {
                return ResourceManager.GetString("AdjustingImage", resourceCulture);
            }
        }
        
        internal static string DesiredArrival {
            get {
                return ResourceManager.GetString("DesiredArrival", resourceCulture);
            }
        }
        
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        internal static string TravelDelayed {
            get {
                return ResourceManager.GetString("TravelDelayed", resourceCulture);
            }
        }
        
        internal static string TransportQuestion {
            get {
                return ResourceManager.GetString("TransportQuestion", resourceCulture);
            }
        }
        
        internal static string ItineraryChange {
            get {
                return ResourceManager.GetString("ItineraryChange", resourceCulture);
            }
        }
        
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        internal static string RewardNoCurrency {
            get {
                return ResourceManager.GetString("RewardNoCurrency", resourceCulture);
            }
        }
        
        internal static string ItemTaken {
            get {
                return ResourceManager.GetString("ItemTaken", resourceCulture);
            }
        }
        
        internal static string ItemTakenbyYou {
            get {
                return ResourceManager.GetString("ItemTakenbyYou", resourceCulture);
            }
        }
        
        internal static string NotEnoughRoom {
            get {
                return ResourceManager.GetString("NotEnoughRoom", resourceCulture);
            }
        }
        
        internal static string AcceptedOnRoute {
            get {
                return ResourceManager.GetString("AcceptedOnRoute", resourceCulture);
            }
        }
        
        internal static string CollectOptions {
            get {
                return ResourceManager.GetString("CollectOptions", resourceCulture);
            }
        }
        
        internal static string AtLeastCollect {
            get {
                return ResourceManager.GetString("AtLeastCollect", resourceCulture);
            }
        }
        
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        internal static string OtherConf {
            get {
                return ResourceManager.GetString("OtherConf", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string RequestsOnRoute {
            get {
                return ResourceManager.GetString("RequestsOnRoute", resourceCulture);
            }
        }
        
        internal static string AproxWeight {
            get {
                return ResourceManager.GetString("AproxWeight", resourceCulture);
            }
        }
        
        internal static string OpenDate {
            get {
                return ResourceManager.GetString("OpenDate", resourceCulture);
            }
        }
        
        internal static string rangedays {
            get {
                return ResourceManager.GetString("rangedays", resourceCulture);
            }
        }
        
        internal static string MyRewards {
            get {
                return ResourceManager.GetString("MyRewards", resourceCulture);
            }
        }
        
        internal static string FlexDelivery {
            get {
                return ResourceManager.GetString("FlexDelivery", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string DeliverArticle {
            get {
                return ResourceManager.GetString("DeliverArticle", resourceCulture);
            }
        }
        
        internal static string NoDeliverArticle {
            get {
                return ResourceManager.GetString("NoDeliverArticle", resourceCulture);
            }
        }
        
        internal static string UpdateAllItems {
            get {
                return ResourceManager.GetString("UpdateAllItems", resourceCulture);
            }
        }
        
        internal static string UpdateAllItemsAndEnd {
            get {
                return ResourceManager.GetString("UpdateAllItemsAndEnd", resourceCulture);
            }
        }
        
        internal static string NoAccepted {
            get {
                return ResourceManager.GetString("NoAccepted", resourceCulture);
            }
        }
        
        internal static string UserStatusBought {
            get {
                return ResourceManager.GetString("UserStatusBought", resourceCulture);
            }
        }
        
        internal static string UserStatusStarted {
            get {
                return ResourceManager.GetString("UserStatusStarted", resourceCulture);
            }
        }
        
        internal static string UserStatusDelivered {
            get {
                return ResourceManager.GetString("UserStatusDelivered", resourceCulture);
            }
        }
        
        internal static string UserStatusEnded {
            get {
                return ResourceManager.GetString("UserStatusEnded", resourceCulture);
            }
        }
        
        internal static string UserStatusDelayed {
            get {
                return ResourceManager.GetString("UserStatusDelayed", resourceCulture);
            }
        }
        
        internal static string NotAllAreUpdated {
            get {
                return ResourceManager.GetString("NotAllAreUpdated", resourceCulture);
            }
        }
        
        internal static string someoneaccepted {
            get {
                return ResourceManager.GetString("someoneaccepted", resourceCulture);
            }
        }
        
        internal static string someoneDelivered {
            get {
                return ResourceManager.GetString("someoneDelivered", resourceCulture);
            }
        }
        
        internal static string TravelerRating {
            get {
                return ResourceManager.GetString("TravelerRating", resourceCulture);
            }
        }
        
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        internal static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        internal static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        internal static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        internal static string VeryGood {
            get {
                return ResourceManager.GetString("VeryGood", resourceCulture);
            }
        }
        
        internal static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        internal static string SendRating {
            get {
                return ResourceManager.GetString("SendRating", resourceCulture);
            }
        }
        
        internal static string RatingDone {
            get {
                return ResourceManager.GetString("RatingDone", resourceCulture);
            }
        }
        
        internal static string OpenChat {
            get {
                return ResourceManager.GetString("OpenChat", resourceCulture);
            }
        }
        
        internal static string NoPossibleDelete {
            get {
                return ResourceManager.GetString("NoPossibleDelete", resourceCulture);
            }
        }
        
        internal static string WhantDelete {
            get {
                return ResourceManager.GetString("WhantDelete", resourceCulture);
            }
        }
        
        internal static string Kilos {
            get {
                return ResourceManager.GetString("Kilos", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string UpdateItem {
            get {
                return ResourceManager.GetString("UpdateItem", resourceCulture);
            }
        }
        
        internal static string InvalidDepArr {
            get {
                return ResourceManager.GetString("InvalidDepArr", resourceCulture);
            }
        }
        
        internal static string TypeMessage {
            get {
                return ResourceManager.GetString("TypeMessage", resourceCulture);
            }
        }
        
        internal static string OneNotification {
            get {
                return ResourceManager.GetString("OneNotification", resourceCulture);
            }
        }
        
        internal static string ClientServiceNot {
            get {
                return ResourceManager.GetString("ClientServiceNot", resourceCulture);
            }
        }
        
        internal static string CreditCardInfo {
            get {
                return ResourceManager.GetString("CreditCardInfo", resourceCulture);
            }
        }
        
        internal static string CardHolder {
            get {
                return ResourceManager.GetString("CardHolder", resourceCulture);
            }
        }
        
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        internal static string CardNumberRequired {
            get {
                return ResourceManager.GetString("CardNumberRequired", resourceCulture);
            }
        }
        
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        internal static string MonthAndYear {
            get {
                return ResourceManager.GetString("MonthAndYear", resourceCulture);
            }
        }
        
        internal static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        internal static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        internal static string NoChargeYet {
            get {
                return ResourceManager.GetString("NoChargeYet", resourceCulture);
            }
        }
        
        internal static string InThatMoment {
            get {
                return ResourceManager.GetString("InThatMoment", resourceCulture);
            }
        }
        
        internal static string Line1 {
            get {
                return ResourceManager.GetString("Line1", resourceCulture);
            }
        }
        
        internal static string PaymentInfo {
            get {
                return ResourceManager.GetString("PaymentInfo", resourceCulture);
            }
        }
        
        internal static string SState {
            get {
                return ResourceManager.GetString("SState", resourceCulture);
            }
        }
        
        internal static string SCity {
            get {
                return ResourceManager.GetString("SCity", resourceCulture);
            }
        }
        
        internal static string SCountry {
            get {
                return ResourceManager.GetString("SCountry", resourceCulture);
            }
        }
        
        internal static string ValidDate {
            get {
                return ResourceManager.GetString("ValidDate", resourceCulture);
            }
        }
        
        internal static string NoStartDate {
            get {
                return ResourceManager.GetString("NoStartDate", resourceCulture);
            }
        }
        
        internal static string NoUpdateDate {
            get {
                return ResourceManager.GetString("NoUpdateDate", resourceCulture);
            }
        }
        
        internal static string NoDeliveredDate {
            get {
                return ResourceManager.GetString("NoDeliveredDate", resourceCulture);
            }
        }
        
        internal static string NoEndtravelDate {
            get {
                return ResourceManager.GetString("NoEndtravelDate", resourceCulture);
            }
        }
        
        internal static string ProcessNotCompleted {
            get {
                return ResourceManager.GetString("ProcessNotCompleted", resourceCulture);
            }
        }
        
        internal static string ProcessQuestions {
            get {
                return ResourceManager.GetString("ProcessQuestions", resourceCulture);
            }
        }
        
        internal static string AppQuestions {
            get {
                return ResourceManager.GetString("AppQuestions", resourceCulture);
            }
        }
        
        internal static string AppComents {
            get {
                return ResourceManager.GetString("AppComents", resourceCulture);
            }
        }
        
        internal static string IHaveAProblem {
            get {
                return ResourceManager.GetString("IHaveAProblem", resourceCulture);
            }
        }
        
        internal static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
    }
}
